Repository kurator-dev/kurator, pull requests merged in 2022-10, with the labels that each got.

#82 update doc
  docs/content/en/docs/Components/karmada.md
  docs/content/en/docs/Getting started/quickstart.md
  docs/install-components/karmada.md
  docs/install-components/karmada_ZH.md
Labels: lgtm, size/L, approved

#87 Istio: improve network mode
  cmd/kurator/app/install/istio/istio.go
  docs/content/en/docs/Components/istio.md
  hack/local-dev-down.sh
  pkg/plugin/istio/install.go
  pkg/plugin/istio/plugin.go
  pkg/plugin/istio/util.go
Labels: lgtm, size/L, approved, kind/feature

#88 istio: fix istio createIstioCacerts
  pkg/plugin/istio/install.go
  pkg/plugin/submariner/plugin.go
Labels: lgtm, size/XS, approved, kind/bug

#90 Make install volcano and prometheus idempotent
  pkg/plugin/prometheus/pulgin.go
  pkg/plugin/volcano/plugin.go
Labels: lgtm, approved, size/M, kind/bug

#91 argocd:make install idempotent
  pkg/plugin/argocd/plugin.go
  pkg/util/kube.go
Labels: lgtm, approved, size/S, kind/bug

#92 bump to golang 1.19
  .github/workflows/ci.yaml
  common/config/.golangci.yml
  go.mod
  hack/golangci-lint.sh
  manifests/manifests.go
  pkg/generic/base.go
Labels: lgtm, approved, size/S, kind/feature

#93 refactor typemeta
  pkg/cert/plugged.go
  pkg/cert/selfsigned.go
  pkg/plugin/istio/install.go
  pkg/plugin/prometheus/pulgin.go
  pkg/plugin/thanos/plugin.go
  pkg/plugin/thanos/thanos.go
  pkg/plugin/volcano/plugin.go
  pkg/typemeta/typemeta.go
  pkg/util/policy.go
  pkg/util/policy_test.go
Labels: lgtm, size/L, approved

#89 istio: fix istio idempotent
  pkg/plugin/istio/install.go
Labels: lgtm, size/XS, approved, kind/bug
