Repository kurator-dev/kurator, pull requests merged in 2022-07, with the labels that each got.

#34 docs: add install karmada docs
  docs/README.md
  docs/install-components/karmada.md
  docs/install-components/karmada_ZH.md
Labels: lgtm, size/L, approved

#33 supports specifying component configuration files
  cmd/kurator/app/app.go
  pkg/generic/options.go
Labels: lgtm, approved, size/M, kind/feature

#35 add docs infra
  .gitignore
  docs/README.md
  docs/config.toml
  docs/content/en/_index.html
  docs/content/en/docs/Components/_index.md
  docs/content/en/docs/Components/karmada.md
  docs/content/en/docs/Getting started/_index.md
  docs/content/en/docs/Getting started/quickstart.md
  docs/content/en/docs/_index.md
  docs/content/en/search.md
  docs/go.mod
  docs/go.sum
Labels: lgtm, size/L, approved, kind/feature

#36 Lint markdown
  .github/workflows/ci.yaml
  Makefile
  docs/README.md
  docs/content/en/docs/Components/_index.md
  docs/content/en/docs/Components/karmada.md
  docs/content/en/docs/Getting started/quickstart.md
  docs/content/en/docs/_index.md
  mdl.json
Labels: lgtm, approved, size/M, kind/feature

#40 fix install Istio not found istiod-elb service error log
  pkg/plugin/istio/install.go
Labels: lgtm, size/XS, approved, kind/bug

#39 Move lint configs from root dir to /common/config
  Makefile
  common/config/.golangci.yml
  common/config/mdl.json
  hack/golangci-lint.sh
Labels: lgtm, size/XS, approved

#44 Local up setup cluster should contains node other than master
  hack/kind-configs/host.yaml
  hack/kind-configs/member1.yaml
  hack/kind-configs/member2.yaml
  hack/local-dev-setup.sh
Labels: lgtm, approved, size/S, kind/feature

#42 Added Submariner Install
  cmd/kurator/app/install/install.go
  cmd/kurator/app/install/submariner/submariner.go
  manifests/profiles/components.yaml
  pkg/plugin/submariner/install.go
  pkg/plugin/submariner/plugin.go
  pkg/util/download.go
Labels: lgtm, size/L, approved

#46 istio support non-flat network
  cmd/kurator/app/install/istio/istio.go
  go.mod
  manifests/profiles/eastwest.tmpl.yaml
  manifests/profiles/expose-services.yaml
  pkg/plugin/istio/install.go
  pkg/plugin/istio/plugin.go
  pkg/plugin/istio/testdata/eastwest.yaml
  pkg/plugin/istio/util.go
  pkg/plugin/istio/util_test.go
Labels: lgtm, size/L, approved, kind/feature
