Repository kurator-dev/kurator, pull requests merged in 2022-06, with the labels that each got.

#3 update OWNERS
  hack/OWNERS
Labels: lgtm, size/XS

#4 update OWNERS
  OWNERS
Labels: size/XS

#2 Set up CI to verify and test each pull request
  .github/workflows/ci.yaml
  Makefile
  hack/golangci-lint.sh
  hack/util.sh
  pkg/plugin/istio/install.go
  pkg/plugin/kubeedge/plugin.go
  pkg/plugin/prometheus/pulgin.go
  pkg/util/policy_test.go
  pkg/util/untar.go
Labels: lgtm, size/L, approved

#8 add golangli configure file
  .golangci.yml
  pkg/moreos/proc.go
  pkg/plugin/join/kubeedge/kubeedge.go
Labels: lgtm, approved, size/M

#9 fix range map
  pkg/plugin/prometheus/pulgin.go
  pkg/plugin/prometheus/util.go
  pkg/plugin/prometheus/util_test.go
Labels: lgtm, approved, size/M

#7 clean go cache to force go test always run
  Makefile
Labels: lgtm, size/XS, approved

#6 Fix make lint error: Circular lint <- lint dependency dropped
  Makefile
Labels: lgtm, size/XS, approved

#5 Rename to NewKuratorCommand
  cmd/kurator/app/app.go
Labels: lgtm, size/XS, approved

#12 CI workflow ut test run in parallel with other jobs
  .github/workflows/ci.yaml
Labels: lgtm, approved

#15 increase golangci timeout
  .golangci.yml
Labels: lgtm, size/XS, approved, kind/feature

#14 add gen check
  .github/workflows/ci.yaml
  Makefile
  hack/gen-check.sh
Labels: lgtm, approved, size/M, kind/feature

#17 add osx trash to gitignore
  .gitignore
Labels: lgtm, size/XS, approved

#18 Add gci linter to format imports
  .golangci.yml
  cmd/kurator/main.go
Labels: lgtm, size/XS, approved

#20 fix make gen-check jb not found
  Makefile
  hack/gen-prom.sh
Labels: lgtm, approved, size/S

#25 fix remove temp-dir flag
  pkg/generic/options.go
  pkg/plugin/istio/install.go
Labels: lgtm, approved, size/S

#27 fix readme
  README.md
Labels: lgtm, size/XS, approved, kind/bug

#28 add log for download
  pkg/util/download.go
Labels: lgtm, size/XS, approved, kind/bug

#31 feat: install support karmada init flag
  cmd/kurator/app/install/karmada/karmada.go
  pkg/plugin/join/plugin.go
  pkg/plugin/karmada/plugin.go
Labels: lgtm, approved, size/S, kind/feature
