Repository kurator-dev/kurator, pull requests merged in 2022-11, with the labels that each got.

#95 pixie: make install idempotent
  pkg/plugin/pixie/vizier/plugin.go
Labels: lgtm, size/XS, approved, kind/bug

#94 kubeedge: make install idempotent
  pkg/plugin/kubeedge/plugin.go
Labels: lgtm, approved, size/S, kind/bug

#100 init cluster-operator
  Makefile
  cmd/cluster-operator/Dockerfile
  cmd/cluster-operator/aws/aws.go
  cmd/cluster-operator/config/aws.go
  cmd/cluster-operator/config/options.go
  cmd/cluster-operator/main.go
  cmd/cluster-operator/scheme/aws.go
  cmd/cluster-operator/scheme/scheme.go
  go.mod
  go.sum
  pkg/cert/selfsigned.go
Labels: lgtm, approved, kind/feature, size/XXL

#101 cluster operator: init helm chart
  Makefile
  cmd/cluster-operator/README.md
  cmd/crd-gen-tool/README.md
  cmd/crd-gen-tool/main.go
  go.mod
  go.sum
  hack/gen-chart.sh
  hack/sync-crds.sh
  manifests/charts/base/Chart.yaml
  manifests/charts/base/templates/awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsclusterroleidentities.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsclusters.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsclusterstaticidentities.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsfargateprofiles.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsmachines.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsmachinetemplates.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/certmanager.yaml
  manifests/charts/base/templates/clusterclasses.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/clusterresourcesetbindings.addons.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/clusterresourcesets.addons.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/clusters.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/eksconfigs.bootstrap.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/eksconfigtemplates.bootstrap.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/machinedeployments.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/machinehealthchecks.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/machinepools.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/machines.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/machinesets.cluster.x-k8s.io.yaml
  manifests/charts/base/values.yaml
  manifests/charts/cluster-operator/Chart.yaml
  manifests/charts/cluster-operator/templates/aws-secret.yaml
  manifests/charts/cluster-operator/templates/deployment.yaml
  manifests/charts/cluster-operator/templates/mutatingwebhook.yaml
  manifests/charts/cluster-operator/templates/rbac.yaml
  manifests/charts/cluster-operator/templates/service.yaml
  manifests/charts/cluster-operator/templates/serviceaccount.yaml
  manifests/charts/cluster-operator/templates/validatingwebhook.yaml
  manifests/charts/cluster-operator/values.yaml
Labels: lgtm, approved, kind/feature, size/XXL

#99 Add basic cluster framework
  Makefile
  common/config/.golangci.yml
  go.mod
  go.sum
  hack/init-codegen.sh
  hack/tool/tool.go
  hack/update-codegen.sh
  pkg/apis/doc.go
Labels: lgtm, size/L, approved, kind/feature

#102 Added cluster api
  Makefile
  hack/update-codegen.sh
  manifests/charts/base/templates/cluster.kurator.dev_customclusters.yaml
  manifests/charts/base/templates/cluster.kurator.dev_custommachines.yaml
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/apis/cluster/v1alpha1/doc.go
  pkg/apis/cluster/v1alpha1/machine.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cluster/v1alpha1/zz_generated.register.go
  pkg/client-go/generated/clientset/versioned/clientset.go
  pkg/client-go/generated/clientset/versioned/doc.go
  pkg/client-go/generated/clientset/versioned/fake/clientset_generated.go
  pkg/client-go/generated/clientset/versioned/fake/doc.go
  pkg/client-go/generated/clientset/versioned/fake/register.go
  pkg/client-go/generated/clientset/versioned/scheme/doc.go
  pkg/client-go/generated/clientset/versioned/scheme/register.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/cluster_client.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/customcluster.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/custommachine.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/doc.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/doc.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_cluster_client.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_customcluster.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_custommachine.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/generated_expansion.go
  pkg/client-go/generated/informers/externalversions/cluster/interface.go
  pkg/client-go/generated/informers/externalversions/cluster/v1alpha1/customcluster.go
  pkg/client-go/generated/informers/externalversions/cluster/v1alpha1/custommachine.go
  pkg/client-go/generated/informers/externalversions/cluster/v1alpha1/interface.go
  pkg/client-go/generated/informers/externalversions/factory.go
  pkg/client-go/generated/informers/externalversions/generic.go
  pkg/client-go/generated/informers/externalversions/internalinterfaces/factory_interfaces.go
  pkg/client-go/generated/listers/cluster/v1alpha1/customcluster.go
  pkg/client-go/generated/listers/cluster/v1alpha1/custommachine.go
  pkg/client-go/generated/listers/cluster/v1alpha1/expansion_generated.go
Labels: size/XXL
