Repository kurator-dev/kurator, pull requests merged in 2022-08, with the labels that each got.

#49 upgrade karmada
  manifests/profiles/components.yaml
Labels: lgtm, size/XS, approved, kind/feature

#50 use kind delete
  hack/local-dev-down.sh
Labels: lgtm, size/XS, approved, kind/bug

#52 Install metalb in host cluster
  hack/local-dev-setup.sh
Labels: size/XS

#56 feat: add tool list subcommand
  cmd/kurator/app/app.go
  cmd/kurator/app/tool/tool.go
  go.mod
  go.sum
  pkg/tool/list.go
  pkg/tool/list_test.go
Labels: lgtm, size/L, approved, kind/feature

#57 remove redundant log
  pkg/generic/options.go
Labels: lgtm, size/XS, approved, kind/bug

#54 Integrate with argoCD to support continuous delivery
  cmd/kurator/app/install/argocd/argocd.go
  cmd/kurator/app/install/install.go
  docs/content/en/docs/Components/argocd.md
  docs/content/en/docs/Components/image/app-source.PNG
  docs/content/en/docs/Components/image/application-page.PNG
  docs/content/en/docs/Components/image/clusters.PNG
  docs/content/en/docs/Components/image/deployment-status.PNG
  docs/content/en/docs/Components/image/login.PNG
  docs/content/en/docs/Components/image/new-app.PNG
  docs/content/en/docs/Components/image/sync-output.PNG
  docs/content/en/docs/Components/image/sync.PNG
  manifests/profiles/components.yaml
  pkg/client/client.go
  pkg/plugin/argocd/plugin.go
  pkg/util/kube.go
Labels: lgtm, approved, size/XL

#62 support pixie vizier
  cmd/kurator/app/install/install.go
  cmd/kurator/app/install/pixie/pixie.go
  cmd/kurator/app/install/pixie/vizier/vizier.go
  manifests/profiles/components.yaml
  pkg/client/client.go
  pkg/client/helmclient.go
  pkg/plugin/istio/install.go
  pkg/plugin/pixie/vizier/plugin.go
Labels: lgtm, size/L, approved, kind/feature

#67 fix volcano installer
  pkg/plugin/volcano/plugin.go
Labels: lgtm, size/XS, approved, kind/bug

#68 [cherrypick]fix volcano installer
  pkg/plugin/volcano/plugin.go
Labels: lgtm, size/XS, approved, kind/bug

#64 improve doc infra
  .github/workflows/ci.yaml
  Makefile
  docs/content/en/docs/Components/argocd.md
  docs/layouts/shortcodes/image.html
  docs/netlify.toml
  docs/package.json
  hack/local-docsite-up.sh
Labels: lgtm, size/L, approved, kind/feature

#70 add Pixie vizier doc
  docs/content/en/docs/Components/image/pixie-admin-page.png
  docs/content/en/docs/Components/image/pixie.png
  docs/content/en/docs/Components/pixie-vizier.md
Labels: lgtm, approved, size/M
