Repository kurator-dev/kurator, pull requests merged in 2022-12, with the labels that each got.

#106 implement custom machine controller
  cmd/cluster-operator/customcluster/customcluster.go
  manifests/charts/base/templates/cluster.kurator.dev_custommachines.yaml
  pkg/apis/cluster/v1alpha1/machine.go
  pkg/controllers/custommachine_controller.go
Labels: size/L

#108 clusteroperator: fix missing rbac
  manifests/charts/cluster-operator/templates/rbac.yaml
Labels: lgtm, approved, size/S, kind/bug

#103 clusteroperator: add controller from capi
  Makefile
  cmd/cluster-operator/Dockerfile
  cmd/cluster-operator/README.md
  cmd/cluster-operator/aws/aws.go
  cmd/cluster-operator/capi/capi.go
  cmd/cluster-operator/config/options.go
  cmd/cluster-operator/main.go
  cmd/cluster-operator/scheme/aws.go
  cmd/cluster-operator/scheme/capi.go
  cmd/crd-gen-tool/main.go
  go.mod
  go.sum
  hack/sync-crds.sh
  manifests/charts/base/templates/awsclustercontrolleridentities.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsclusterroleidentities.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsclusters.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsclusterstaticidentities.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsclustertemplates.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsfargateprofiles.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsmachinepools.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsmachines.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsmachinetemplates.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsmanagedclusters.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsmanagedcontrolplanes.controlplane.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/awsmanagedmachinepools.infrastructure.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/clusterclasses.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/clusterresourcesetbindings.addons.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/clusterresourcesets.addons.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/clusters.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/eksconfigs.bootstrap.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/eksconfigtemplates.bootstrap.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/extensionconfigs.runtime.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/ipaddressclaims.ipam.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/ipaddresses.ipam.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/kubeadmconfigs.bootstrap.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/kubeadmconfigtemplates.bootstrap.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/kubeadmcontrolplanes.controlplane.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/kubeadmcontrolplanetemplates.controlplane.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/machinedeployments.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/machinehealthchecks.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/machinepools.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/machines.cluster.x-k8s.io.yaml
  manifests/charts/base/templates/machinesets.cluster.x-k8s.io.yaml
  manifests/charts/cluster-operator/templates/_helpers.tpl
  manifests/charts/cluster-operator/templates/aws-secret.yaml
  manifests/charts/cluster-operator/templates/capa-mutating-webhook-configuration.yaml
  manifests/charts/cluster-operator/templates/capa-validating-webhook-configuration.yaml
  manifests/charts/cluster-operator/templates/capi-kubeadm-bootstrap-mutating-webhook-configuration.yaml
  manifests/charts/cluster-operator/templates/capi-kubeadm-bootstrap-validating-webhook-configuration.yaml
  manifests/charts/cluster-operator/templates/capi-kubeadm-control-plane-mutating-webhook-configuration.yaml
  manifests/charts/cluster-operator/templates/capi-kubeadm-control-plane-validating-webhook-configuration.yaml
  manifests/charts/cluster-operator/templates/capi-mutating-webhook-configuration.yaml
  manifests/charts/cluster-operator/templates/capi-validating-webhook-configuration.yaml
  manifests/charts/cluster-operator/templates/deployment.yaml
  manifests/charts/cluster-operator/templates/leader-rbac.yaml
  manifests/charts/cluster-operator/templates/rbac.yaml
  manifests/charts/cluster-operator/values.yaml
  manifests/examples/capi-quickstart.yaml
Labels: lgtm, approved, kind/feature, size/XXL

#109 clusteroperator: update doc
  docs/content/en/docs/Cluster operator/_index.md
  docs/content/en/docs/Cluster operator/image/capa-aws.png
  docs/content/en/docs/Cluster operator/quickstart.md
  docs/content/en/docs/Components/_index.md
  docs/content/en/docs/Getting started/_index.md
  docs/content/en/docs/Getting started/quickstart.md
  hack/local-setup-cluster.sh
  manifests/examples/capi-quickstart.yaml
Labels: lgtm, size/L, approved

#110 clusteroperator: update doc
  cmd/cluster-operator/README.md
  docs/content/en/docs/Cluster operator/image/capa-crd.png
  docs/content/en/docs/Cluster operator/quickstart.md
  manifests/charts/cluster-operator/values.yaml
  manifests/examples/multi-tenancy/capi-multitenancy.yaml
Labels: lgtm, size/L, approved

#111 supplement cluster operator introduction
  docs/content/en/docs/Cluster operator/_index.md
  docs/content/en/docs/Cluster operator/image/cluster-operator.png
Labels: lgtm, approved, size/S
