Repository kurator-dev/kurator, pull requests merged in 2023-02, with the labels that each got.

#138 fix panic: service-endpoints flag redefined
  cmd/cluster-operator/options/options.go
Labels: lgtm, size/XS, approved, kind/bug

#137 update gitignore
  .gitignore
Labels: lgtm, size/XS, approved

#114 Basic implementation of customeCluster controller
  cmd/cluster-operator/customcluster/customcluster.go
  hack/update-crdgen.sh
  manifests/charts/base/templates/cluster.kurator.dev_customclusters.yaml
  manifests/charts/cluster-operator/templates/rbac.yaml
  manifests/charts/kustomization.yaml
  manifests/examples/customcluster/cc-cluster.yaml
  manifests/examples/customcluster/cc-customcluster.yaml
  manifests/examples/customcluster/cc-custommachine.yaml
  manifests/examples/customcluster/cc-kcp.yaml
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/customcluster_controller.go
  pkg/controllers/customcluster_controller_test.go
  pkg/controllers/custommachine_controller.go
Labels: lgtm, approved, size/XXL

#115 Add doc of cluster lifecycle management on VMs
  docs/content/en/docs/Cluster operator/aws-deploy.md
  docs/content/en/docs/Cluster operator/vms-deploy.md
Labels: lgtm, size/L, approved

#139 update chart version
  Makefile
Labels: lgtm, approved

#140 fix make chart
  Makefile
  hack/gen-chart.sh
  manifests/charts/cluster-operator/values.yaml
Labels: lgtm, size/XS, approved, kind/bug

#142 [release-0.2] fix make chart
  Makefile
  hack/gen-chart.sh
  manifests/charts/cluster-operator/values.yaml
Labels: lgtm, size/XS, approved

#134 add infra api
  Makefile
  hack/local-dev-setup.sh
  hack/local-docsite-up.sh
  hack/update-codegen.sh
  hack/update-crdgen.sh
  manifests/charts/base/templates/infra.kurator.dev_clusters.yaml
  pkg/apis/infra/v1alpha1/cluster_types.go
  pkg/apis/infra/v1alpha1/doc.go
  pkg/apis/infra/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/infra/v1alpha1/zz_generated.register.go
  pkg/client-go/generated/clientset/versioned/clientset.go
  pkg/client-go/generated/clientset/versioned/fake/clientset_generated.go
  pkg/client-go/generated/clientset/versioned/fake/register.go
  pkg/client-go/generated/clientset/versioned/scheme/register.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/cluster.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/doc.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/doc.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/fake_cluster.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/fake_infra_client.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/generated_expansion.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/infra_client.go
  pkg/client-go/generated/informers/externalversions/factory.go
  pkg/client-go/generated/informers/externalversions/generic.go
  pkg/client-go/generated/informers/externalversions/infra/interface.go
  pkg/client-go/generated/informers/externalversions/infra/v1alpha1/cluster.go
  pkg/client-go/generated/informers/externalversions/infra/v1alpha1/interface.go
  pkg/client-go/generated/listers/infra/v1alpha1/cluster.go
  pkg/client-go/generated/listers/infra/v1alpha1/expansion_generated.go
Labels: lgtm, approved, kind/feature, size/XXL

#144 infra api: add categories
  manifests/charts/base/templates/infra.kurator.dev_clusters.yaml
  pkg/apis/infra/v1alpha1/cluster_types.go
Labels: lgtm, approved, size/S

#146 init infra cluster controller
  cmd/cluster-operator/capi/capi.go
  cmd/cluster-operator/infra/infra.go
  cmd/cluster-operator/main.go
  cmd/cluster-operator/scheme/scheme.go
  go.mod
  manifests/charts/cluster-operator/templates/rbac.yaml
  pkg/controllers/infra/cluster_controller.go
Labels: lgtm, size/L, approved, kind/feature

#154 makefile: move to v0.3-dev
  .github/workflows/release-master.yaml
  Makefile
  hack/gen-chart.sh
  manifests/charts/base/Chart.yaml
  manifests/charts/cluster-operator/Chart.yaml
Labels: lgtm, approved, size/S

#155 Added subdir {hack, manifests} owners
  hack/OWNERS
  manifests/OWNERS
Labels: lgtm, approved, size/S

#156 Pass correct worker concurrency
  cmd/cluster-operator/customcluster/customcluster.go
  cmd/cluster-operator/main.go
Labels: lgtm, size/XS, approved, kind/bug

#157 infraapi: correct condition type
  manifests/charts/base/templates/infra.kurator.dev_clusters.yaml
  pkg/apis/infra/v1alpha1/cluster_types.go
  pkg/apis/infra/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/infra/cluster_controller.go
Labels: lgtm, size/L, approved, kind/api-change

#158 reorg docs
  docs/config.toml
  docs/content/en/docs/Cluster operator/aws-deploy.md
  docs/content/en/docs/Cluster operator/includes/build-from-source.md.tpl
  docs/content/en/docs/Cluster operator/includes/cleanup.tpl
  docs/content/en/docs/Cluster operator/includes/prepare-aws.tpl
  docs/content/en/docs/Cluster operator/includes/prerequisites.tpl
Labels: lgtm, size/L, approved

#161 docs: publish to Github Pages
  .github/workflows/docs.yaml
  .gitignore
  Makefile
  hack/local-docsite-build.sh
Labels: lgtm, approved, size/M, kind/documentation

#159 docs: fix filename
  docs/content/en/docs/Cluster operator/includes/build-from-source.tpl
Labels: lgtm, size/XS, approved, kind/documentation

#163 CustomMachine cleanup
  manifests/charts/base/templates/cluster.kurator.dev_customclusters.yaml
  manifests/charts/base/templates/cluster.kurator.dev_custommachines.yaml
  manifests/charts/base/templates/infra.kurator.dev_clusters.yaml
  pkg/apis/cluster/v1alpha1/cluster.go
  pkg/apis/cluster/v1alpha1/machine.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/infra/v1alpha1/cluster_types.go
Labels: lgtm, approved, size/M

#164 Updating api group
  hack/update-crdgen.sh
  manifests/charts/base/templates/cluster.kurator.dev_clusters.yaml
  manifests/charts/base/templates/infrastructure.cluster.x-k8s.io_customclusters.yaml
  manifests/charts/base/templates/infrastructure.cluster.x-k8s.io_custommachines.yaml
  manifests/charts/kustomization.yaml
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cluster/v1alpha1/zz_generated.register.go
  pkg/apis/infra/v1alpha1/cluster.go
  pkg/apis/infra/v1alpha1/doc.go
  pkg/apis/infra/v1alpha1/machine.go
  pkg/apis/infra/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/infra/v1alpha1/zz_generated.register.go
  pkg/client-go/generated/clientset/versioned/clientset.go
  pkg/client-go/generated/clientset/versioned/fake/clientset_generated.go
  pkg/client-go/generated/clientset/versioned/fake/register.go
  pkg/client-go/generated/clientset/versioned/scheme/register.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/cluster.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/cluster_client.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_cluster.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_cluster_client.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/generated_expansion.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/customcluster.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/custommachine.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/fake_customcluster.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/fake_custommachine.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/fake_infra_client.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/generated_expansion.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/infra_client.go
  pkg/client-go/generated/informers/externalversions/cluster/v1alpha1/cluster.go
  pkg/client-go/generated/informers/externalversions/cluster/v1alpha1/interface.go
  pkg/client-go/generated/informers/externalversions/factory.go
  pkg/client-go/generated/informers/externalversions/generic.go
  pkg/client-go/generated/informers/externalversions/infra/v1alpha1/customcluster.go
  pkg/client-go/generated/informers/externalversions/infra/v1alpha1/custommachine.go
  pkg/client-go/generated/informers/externalversions/infra/v1alpha1/interface.go
  pkg/client-go/generated/listers/cluster/v1alpha1/cluster.go
  pkg/client-go/generated/listers/cluster/v1alpha1/expansion_generated.go
  pkg/client-go/generated/listers/infra/v1alpha1/customcluster.go
  pkg/client-go/generated/listers/infra/v1alpha1/custommachine.go
  pkg/client-go/generated/listers/infra/v1alpha1/expansion_generated.go
  pkg/controllers/customcluster_controller.go
  pkg/controllers/customcluster_controller_test.go
  pkg/controllers/custommachine_controller.go
  pkg/controllers/infra/cluster_controller.go
Labels: lgtm, approved, size/XXL, kind/api-change

#166 github action: use ubuntu-22.04
  .github/workflows/ci.yaml
  .github/workflows/docs.yaml
  .github/workflows/release-master.yaml
  hack/local-dev-setup.sh
  hack/local-setup-cluster.sh
Labels: lgtm, approved, size/S, kind/feature

#167 Added kubeconfig in Cluster and CustomCluster status
  manifests/charts/base/templates/cluster.kurator.dev_clusters.yaml
  manifests/charts/base/templates/infrastructure.cluster.x-k8s.io_customclusters.yaml
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/infra/v1alpha1/cluster.go
  pkg/apis/infra/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, size/M, kind/api-change

#160 implement infra cluster controller
  cmd/cluster-operator/infra/infra.go
  docs/content/en/docs/Cluster operator/includes/install-cluster-operator.tpl
  docs/content/en/docs/Cluster operator/infra-api.md
  go.mod
  go.sum
  manifests/charts/cluster-operator/templates/rbac.yaml
  manifests/examples/infra/additionalresources.yaml
  manifests/examples/infra/quickstart.yaml
  manifests/manifests.go
  manifests/profiles/infra/capitpls/aws.yaml.tpl
  manifests/profiles/infra/plugins/aws-cni-calico.yaml
  pkg/apis/cluster/v1alpha1/cluster_consts.go
  pkg/controllers/infra/cluster_controller.go
  pkg/infra/plugin/plugin.go
  pkg/infra/plugin/plugin.yaml.tpl
  pkg/infra/plugin/plugin_test.go
  pkg/infra/plugin/testdata/aws-cni-calico.yaml
  pkg/infra/provider.go
  pkg/infra/scope/cluster.go
  pkg/infra/template/aws.go
  pkg/infra/template/aws_test.go
  pkg/infra/template/testdata/capa-quickstart.yaml
  pkg/infra/template/testdata/enable-podidentity.yaml
  pkg/infra/template/testdata/without-sshkey.yaml
  pkg/infra/util/util.go
  pkg/infra/util/util_test.go
  pkg/typemeta/typemeta.go
Labels: lgtm, approved, kind/feature, size/XXL

#168 update cluster operator docs and examples
  docs/content/en/docs/Cluster operator/aws-deploy.md
  docs/content/en/docs/Cluster operator/vms-deploy.md
  manifests/charts/cluster-operator/templates/deployment.yaml
  manifests/examples/customcluster/cc-cluster.yaml
  manifests/examples/customcluster/cc-customcluster.yaml
  manifests/examples/customcluster/cc-custommachine.yaml
  manifests/examples/customcluster/cc-kcp.yaml
Labels: lgtm, approved, size/M, kind/documentation

#173 chore: do not clean cache before build
  Makefile
Labels: lgtm, size/XS, approved
