Repository kurator-dev/kurator, pull requests merged in 2023-04, with the labels that each got.

#220 Update 2023 roadmap
  ROADMAP.md
Labels: lgtm, approved, size/M, kind/documentation

#219 customcluster: refactor to reduce file size of controller.go
  pkg/apis/infra/v1alpha1/cluster.go
  pkg/controllers/customcluster_clusterconfig.template
  pkg/controllers/customcluster_clusterhosts.template
  pkg/controllers/customcluster_controller.go
  pkg/controllers/customcluster_helper.go
  pkg/controllers/customcluster_helper_test.go
  pkg/controllers/customcluster_scale.go
  pkg/controllers/customcluster_scale_test.go
Labels: lgtm, approved, size/XXL

#223 chore: fix copyright
  hack/gen-chart.sh
  hack/lint_copyright_banner.sh
  hack/sync-crds.sh
  manifests/manifests.go
Labels: lgtm, approved, size/M

#209 customcluster: realization of upgrading of cluster version
  examples/infra/customcluster/cc-kcp.yaml
  go.mod
  pkg/apis/infra/v1alpha1/cluster.go
  pkg/controllers/customcluster_controller.go
  pkg/controllers/customcluster_helper.go
  pkg/controllers/customcluster_helper_test.go
  pkg/controllers/customcluster_upgrade.go
  pkg/controllers/customcluster_upgrade_test.go
Labels: lgtm, size/L, approved, kind/feature, tide/merge-method-squash, /cherry-pick release-0.3

#208 Added fleet api
  Makefile
  cmd/fleet-manager/Dockerfile
  cmd/fleet-manager/main.go
  cmd/fleet-manager/options/options.go
  cmd/fleet-manager/scheme/scheme.go
  examples/fleet/fleet.yaml
  examples/fleet/quickstart.yaml
  fake-cluster.kubeconfig
  go.mod
  go.sum
  hack/update-codegen.sh
  hack/update-crdgen.sh
  manifests/charts/fleet-manager/Chart.yaml
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleet.yaml
  manifests/charts/fleet-manager/templates/deployment.yaml
  manifests/charts/fleet-manager/templates/fleet-worker-clusterrole.yaml
  manifests/charts/fleet-manager/templates/rbac.yaml
  manifests/charts/fleet-manager/templates/serviceaccount.yaml
  manifests/charts/fleet-manager/values.yaml
  pkg/apis/fleet/v1alpha1/doc.go
  pkg/apis/fleet/v1alpha1/types.go
  pkg/apis/fleet/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/fleet/v1alpha1/zz_generated.register.go
  pkg/client-go/generated/clientset/versioned/clientset.go
  pkg/client-go/generated/clientset/versioned/fake/clientset_generated.go
  pkg/client-go/generated/clientset/versioned/fake/register.go
  pkg/client-go/generated/clientset/versioned/scheme/register.go
  pkg/client-go/generated/clientset/versioned/typed/fleet/v1alpha1/doc.go
  pkg/client-go/generated/clientset/versioned/typed/fleet/v1alpha1/fake/doc.go
  pkg/client-go/generated/clientset/versioned/typed/fleet/v1alpha1/fake/fake_fleet.go
  pkg/client-go/generated/clientset/versioned/typed/fleet/v1alpha1/fake/fake_fleet_client.go
  pkg/client-go/generated/clientset/versioned/typed/fleet/v1alpha1/fleet.go
  pkg/client-go/generated/clientset/versioned/typed/fleet/v1alpha1/fleet_client.go
  pkg/client-go/generated/clientset/versioned/typed/fleet/v1alpha1/generated_expansion.go
  pkg/client-go/generated/informers/externalversions/factory.go
  pkg/client-go/generated/informers/externalversions/fleet/interface.go
  pkg/client-go/generated/informers/externalversions/fleet/v1alpha1/fleet.go
  pkg/client-go/generated/informers/externalversions/fleet/v1alpha1/interface.go
  pkg/client-go/generated/informers/externalversions/generic.go
  pkg/client-go/generated/listers/fleet/v1alpha1/expansion_generated.go
  pkg/client-go/generated/listers/fleet/v1alpha1/fleet.go
  pkg/fleet-manager/clusters.go
  pkg/fleet-manager/controlplane.go
  pkg/fleet-manager/fleet.go
Labels: lgtm, approved, kind/feature, size/XXL, kind/api-change

#224 customcluster: support kube-vip to achieve HA
  docs/content/en/references/infra_types.md
  manifests/charts/cluster-operator/crds/infrastructure.cluster.x-k8s.io_customclusters.yaml
  pkg/apis/infra/v1alpha1/cluster.go
  pkg/apis/infra/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/customcluster_clusterconfig.template
  pkg/controllers/customcluster_helper.go
Labels: lgtm, approved, size/M, kind/feature

#238 Fleet manager misc fix
  cmd/fleet-manager/main.go
  cmd/fleet-manager/options/options.go
  hack/gen-chart.sh
  manifests/charts/fleet-manager/templates/deployment.yaml
Labels: lgtm, approved, size/S

#214 doc:add customcluster kubernetes version upgrade
  docs/content/en/docs/cluster-operator/vms-cluster-lifecycle.md
Labels: lgtm, approved, size/M, kind/documentation

#242 Added cluster update event trigger fleet reconcile
  pkg/fleet-manager/clusters.go
  pkg/fleet-manager/fleet.go
Labels: lgtm, approved, size/S

#222 make release-artifacts
  Makefile
  hack/release-artifacts.sh
Labels: lgtm, approved, size/M, cherrypick/release-0.3

#241 doc: customcluster kube-vip HA mode
  docs/content/en/docs/cluster-operator/vms-cluster-lifecycle.md
Labels: lgtm, approved, size/M, kind/documentation, cherrypick/release-0.3

#252 customcluster:bug fix
  pkg/controllers/customcluster_controller.go
  pkg/controllers/customcluster_helper.go
Labels: lgtm, approved, size/S, kind/bug

#255 gen api docs for fleet
  docs/content/en/docs/references/fleet-api.md
  docs/content/en/references/fleet_types.md
  hack/gen-api-doc.sh
Labels: lgtm, approved, size/M, kind/documentation, cherrypick/release-0.3

#227 Update readme
  README.md
  common/config/mdl.json
  docs/images/kurator.png
Labels: lgtm, size/L, approved

#254 customcluster: refactor unit test
  pkg/controllers/customcluster_helper_test.go
  pkg/controllers/customcluster_scale_test.go
Labels: lgtm, size/L, approved

#259 bump version
  Makefile
Labels: lgtm, size/XS, approved

#258 Added fleet manager docs
  docs/content/en/boilerplates/install-fleet-manager.md
  docs/content/en/docs/fleet-manager/_index.md
  docs/content/en/docs/fleet-manager/create-fleet.md
  docs/content/en/docs/fleet-manager/image/fleet-manager.svg
  docs/content/en/docs/setup/install-fleet-manager.md
Labels: lgtm, size/L, approved

#262 ci: setup action for release chart
  .github/workflows/release-charts.yaml
  common/config/.cr.yaml
Labels: lgtm, approved, size/M, kind/feature

#264 chore: fix permission
  .github/workflows/release-charts.yaml
Labels: lgtm, size/XS, approved

#266 chore: update action
  .github/workflows/ci.yaml
  .github/workflows/release-master.yaml
Labels: lgtm, approved, size/S, kind/feature

#267 clusteroperator: infraType is immutable
  pkg/webhooks/cluster_webhook.go
  pkg/webhooks/cluster_webhook_test.go
Labels: lgtm, approved, size/M, kind/bug

#268 doc: make better display
  docs/config.toml
  docs/content/en/docs/references/cluster-api.md
  docs/content/en/docs/references/fleet-api.md
  docs/content/en/docs/references/infra-api.md
  docs/content/en/references/cluster_types.md
  docs/content/en/references/cluster_v1alpha1_types.html
  docs/content/en/references/fleet_types.md
  docs/content/en/references/fleet_v1alpha1_types.html
  docs/content/en/references/infra_types.md
  docs/content/en/references/infra_v1alpha1_types.html
  docs/layouts/shortcodes/reference.html
  hack/api-docs/config.json
  hack/api-docs/template/members.tpl
  hack/api-docs/template/pkg.tpl
  hack/api-docs/template/type.tpl
  hack/gen-api-doc.sh
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/apis/fleet/v1alpha1/types.go
Labels: lgtm, approved, size/XXL, kind/documentation

#269 remove config for test
  fake-cluster.kubeconfig
Labels: lgtm, approved, size/S, kind/cleanup

#272 chore: fix gen-api-doc
  hack/gen-api-doc.sh
Labels: lgtm, size/XS, approved

#271 Using phase from fleet api
  docs/content/en/references/fleet_v1alpha1_types.html
  pkg/apis/fleet/v1alpha1/types.go
  pkg/fleet-manager/controlplane.go
  pkg/fleet-manager/fleet.go
Labels: lgtm, approved, size/M

#274 Added AttachedCluster API Schema
  docs/content/en/references/cluster_v1alpha1_types.html
  manifests/charts/cluster-operator/crds/cluster.kurator.dev_attachedclusters.yaml
  pkg/apis/cluster/v1alpha1/attached_cluster_types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/cluster/v1alpha1/zz_generated.register.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/attachedcluster.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/cluster_client.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_attachedcluster.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_cluster_client.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/generated_expansion.go
  pkg/client-go/generated/informers/externalversions/cluster/v1alpha1/attachedcluster.go
  pkg/client-go/generated/informers/externalversions/cluster/v1alpha1/interface.go
  pkg/client-go/generated/informers/externalversions/generic.go
  pkg/client-go/generated/listers/cluster/v1alpha1/attachedcluster.go
  pkg/client-go/generated/listers/cluster/v1alpha1/expansion_generated.go
Labels: lgtm, approved, size/XL, kind/api-change

#275 aws: fix bucket access block
  pkg/infra/aws/bucket/aws_test.go
  pkg/infra/aws/bucket/s3.go
Labels: lgtm, approved, size/M, kind/bug

#277 customcluster:support kubeImageRepo and cluster setting config
  docs/content/en/docs/cluster-operator/vms-cluster-lifecycle.md
  examples/infra/customcluster/cc-cluster.yaml
  examples/infra/customcluster/cc-kcp.yaml
  pkg/controllers/customcluster_clusterconfig.template
  pkg/controllers/customcluster_helper.go
Labels: lgtm, approved, size/M, kind/feature

#278 customcluster: support more ha config
  docs/content/en/docs/cluster-operator/vms-cluster-lifecycle.md
  docs/content/en/references/infra_v1alpha1_types.html
  manifests/charts/cluster-operator/crds/infrastructure.cluster.x-k8s.io_customclusters.yaml
  pkg/apis/infra/v1alpha1/cluster.go
  pkg/controllers/customcluster_clusterconfig.template
  pkg/controllers/customcluster_helper.go
Labels: lgtm, approved, size/M, kind/feature

#279 customcluster: fetch provisioned cluster kubeconfig
  go.mod
  go.sum
  pkg/controllers/customcluster_controller.go
  pkg/controllers/customcluster_helper.go
Labels: lgtm, size/L, approved, kind/feature
