Repository kurator-dev/kurator, pull requests merged in 2023-01, with the labels that each got.

#113 update readme
  README.md
  docs/content/en/docs/Getting started/quickstart.md
Labels: lgtm, approved, size/M

#116 add multi nodes example
  docs/content/en/docs/Cluster operator/quickstart.md
  manifests/examples/multi-nodes/multi-nodes.yaml
Labels: lgtm, size/L, approved

#119 fix make gen
  Makefile
Labels: lgtm, size/XS, approved, kind/bug

#117 clusteroperator: remove unused features
  cmd/cluster-operator/aws/aws.go
  cmd/cluster-operator/capi/capi.go
  go.mod
  go.sum
  manifests/charts/cluster-operator/values.yaml
Labels: lgtm, size/L, approved

#123 Added cluster-operator version sub command
  cmd/cluster-operator/main.go
Labels: lgtm, approved, size/S

#125 ci: push latest image to `ghcr.io`
  .github/workflows/ci.yaml
  .github/workflows/release.yaml
  Makefile
Labels: lgtm, approved, size/M

#126 ci: rename job
  .github/workflows/release.yaml
Labels: lgtm, size/XS, approved

#127 Cleanup makefile
  Makefile
  hack/util.sh
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, size/S

#124 Cleanup cluster operator options
  cmd/cluster-operator/aws/aws.go
  cmd/cluster-operator/capi/capi.go
  cmd/cluster-operator/main.go
  cmd/cluster-operator/options/aws.go
  cmd/cluster-operator/options/options.go
Labels: lgtm, approved, size/M

#132 update cluster operator doc
  docs/content/en/docs/Cluster operator/quickstart.md
Labels: lgtm, approved, size/M

#133 makefile: improve gen-crd
  Makefile
  hack/update-crdgen.sh
Labels: lgtm, approved, size/S
