Repository kurator-dev/kurator, pull requests merged in 2023-12, with the labels that each got.

#495 Fixed function name error
  pkg/fleet-manager/fleet_plugin_distributedstorage.go
  pkg/fleet-manager/plugin/plugin.go
  pkg/fleet-manager/plugin/plugin_test.go
Labels: lgtm, size/XS, approved, kind/bug

#492 refactor: make buildFleetClusters public
  pkg/fleet-manager/backup_restore_migrate_shared.go
  pkg/fleet-manager/fleet.go
  pkg/fleet-manager/fleet_cluster.go
Labels: lgtm, size/XS, approved, kind/cleanup

#494 pipeline: add renderRBAC func
  pkg/fleet-manager/pipeline/render/manifests/rbac/rbac.tpl
  pkg/fleet-manager/pipeline/render/rbac.go
  pkg/fleet-manager/pipeline/render/rbac_test.go
  pkg/fleet-manager/pipeline/render/testdata/rbac/default-example.yaml
  pkg/fleet-manager/pipeline/render/util.go
Labels: lgtm, size/L, approved, kind/feature, tide/merge-method-squash

#502 doc: add backup api reference
  docs/content/en/docs/references/backup-api.md
Labels: lgtm, size/XS, approved, kind/documentation

#500 add a community membership guidelines
  community/membership/community-membership.md
Labels: lgtm, approved, size/M, kind/documentation

#504 refactor: add getruntimeclient func
  pkg/fleet-manager/backup_restore_migrate_shared.go
  pkg/fleet-manager/fleet_cluster.go
  pkg/fleet-manager/fleet_plugin_backup.go
Labels: lgtm, approved, size/S, kind/cleanup

#478 pipeline: Init pipeline api
  docs/content/en/references/pipeline_v1alpha1_types.html
  hack/gen-api-doc.sh
  hack/update-codegen.sh
  hack/update-crdgen.sh
  manifests/charts/fleet-manager/crds/pipeline.kurator.dev_pipelines.yaml
  pkg/apis/pipeline/v1alpha1/doc.go
  pkg/apis/pipeline/v1alpha1/type.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/pipeline/v1alpha1/zz_generated.register.go
  pkg/client-go/generated/clientset/versioned/clientset.go
  pkg/client-go/generated/clientset/versioned/fake/clientset_generated.go
  pkg/client-go/generated/clientset/versioned/fake/register.go
  pkg/client-go/generated/clientset/versioned/scheme/register.go
  pkg/client-go/generated/clientset/versioned/typed/apps/v1alpha1/fake/fake_application.go
  pkg/client-go/generated/clientset/versioned/typed/backups/v1alpha1/fake/fake_backup.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_attachedcluster.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_cluster.go
  pkg/client-go/generated/clientset/versioned/typed/fleet/v1alpha1/fake/fake_fleet.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/fake_customcluster.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/fake_custommachine.go
  pkg/client-go/generated/clientset/versioned/typed/pipeline/v1alpha1/doc.go
  pkg/client-go/generated/clientset/versioned/typed/pipeline/v1alpha1/fake/doc.go
  pkg/client-go/generated/clientset/versioned/typed/pipeline/v1alpha1/fake/fake_pipeline.go
  pkg/client-go/generated/clientset/versioned/typed/pipeline/v1alpha1/fake/fake_pipeline_client.go
  pkg/client-go/generated/clientset/versioned/typed/pipeline/v1alpha1/generated_expansion.go
  pkg/client-go/generated/clientset/versioned/typed/pipeline/v1alpha1/pipeline.go
  pkg/client-go/generated/clientset/versioned/typed/pipeline/v1alpha1/pipeline_client.go
  pkg/client-go/generated/informers/externalversions/factory.go
  pkg/client-go/generated/informers/externalversions/generic.go
  pkg/client-go/generated/informers/externalversions/pipeline/interface.go
  pkg/client-go/generated/informers/externalversions/pipeline/v1alpha1/interface.go
  pkg/client-go/generated/informers/externalversions/pipeline/v1alpha1/pipeline.go
  pkg/client-go/generated/listers/pipeline/v1alpha1/expansion_generated.go
  pkg/client-go/generated/listers/pipeline/v1alpha1/pipeline.go
Labels: lgtm, approved, kind/feature, size/XXL, kind/api-change, tide/merge-method-squash

#509 ci: make gen-code work properly
  .gitignore
  Makefile
  Makefile.tools.mk
  hack/gen-api-doc.sh
  hack/gen-chart.sh
  hack/gen-prom.sh
  hack/gen-thanos.sh
  hack/golangci-lint.sh
  hack/init-codegen.sh
  hack/init-gen-tools.sh
  hack/local-dev-setup.sh
  hack/local-setup-cluster.sh
  hack/release-artifacts.sh
  hack/sync-crds.sh
  hack/update-codegen.sh
  hack/update-crdgen.sh
Labels: lgtm, size/L, approved, kind/bug, tide/merge-method-squash

#503 refactor fleet-manager folder
  cmd/fleet-manager/application/application.go
  cmd/fleet-manager/backup/backup.go
  pkg/fleet-manager/application/controller.go
  pkg/fleet-manager/application/helper.go
  pkg/fleet-manager/backup/backup_controller.go
  pkg/fleet-manager/backup/backup_controller_test.go
  pkg/fleet-manager/backup/migrate_controller.go
  pkg/fleet-manager/backup/restore_controller.go
  pkg/fleet-manager/backup/shared.go
  pkg/fleet-manager/backup/shared_test.go
  pkg/fleet-manager/backup/testdata/backup/include-ns.yaml
  pkg/fleet-manager/backup/testdata/backup/label-selector.yaml
  pkg/fleet-manager/backup/testdata/backup/schedule.yaml
  pkg/fleet-manager/backup/testdata/restore/custom-policy.yaml
  pkg/fleet-manager/backup/testdata/restore/minimal.yaml
Labels: lgtm, size/L, approved, kind/cleanup

#512 update readme for fix markdown lint
  README.md
Labels: lgtm, size/XS, approved, kind/bug, kind/documentation, tide/merge-method-squash

#519 init fleet api to install flagger and testloader
  docs/content/en/references/fleet_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleet.yaml
  pkg/apis/fleet/v1alpha1/types.go
  pkg/apis/fleet/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/L, approved, kind/feature, kind/api-change

#524 Make some fleet manager private functions public.
  pkg/fleet-manager/fleet_cluster.go
  pkg/fleet-manager/fleet_plugin_backup.go
  pkg/fleet-manager/fleet_plugin_metric.go
Labels: lgtm, approved, size/M, kind/cleanup

#525 kurator cli: update install cli doc
  docs/content/en/docs/setup/insatll-kurator.md
  docs/content/en/docs/setup/install-cluster-operator.md
Labels: lgtm, approved, size/M, kind/documentation

#520 add rollout status in app api
  docs/content/en/references/apps_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/apps.kurator.dev_applications.yaml
  pkg/apis/apps/v1alpha1/types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/L, approved, kind/api-change

#523 init fleet plugin install flagger and public testloader
  docs/content/en/references/fleet_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleet.yaml
  pkg/apis/fleet/v1alpha1/types.go
  pkg/fleet-manager/fleet_plugin.go
  pkg/fleet-manager/fleet_plugin_flagger.go
  pkg/fleet-manager/manifests/plugins/flagger.yaml
  pkg/fleet-manager/manifests/plugins/testloader.yaml
  pkg/fleet-manager/plugin/plugin.go
  pkg/fleet-manager/plugin/plugin_test.go
  pkg/fleet-manager/plugin/testdata/rollout/default.yaml
  pkg/fleet-manager/plugin/testdata/rollout/testloader-default.yaml
Labels: lgtm, size/L, approved, kind/feature, tide/merge-method-squash

#527 add tekton scheme to runtimeclient
  go.mod
  go.sum
  pkg/client/client.go
Labels: lgtm, size/L, approved, kind/feature, tide/merge-method-squash

#530 Change `[]RolloutStatus` in ApplicationSyncStatus to `RolloutStatus`
  docs/content/en/references/apps_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/apps.kurator.dev_applications.yaml
  pkg/apis/apps/v1alpha1/types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/L, approved, kind/api-change

#531 update fleet-manager rbac.yaml
  manifests/charts/fleet-manager/templates/rbac.yaml
Labels: lgtm, approved, size/M, kind/feature

#448 site: make doc menu more compact
  docs/config.toml
Labels: lgtm, size/XS, approved, kind/documentation

#532 add flaggerapi and appsv1 to ctrlRuntimeClient scheme
  pkg/client/client.go
Labels: lgtm, approved, size/S, kind/feature

#501 add membership request issue template
  .github/ISSUE_TEMPLATE/membership-request.md
Labels: lgtm, approved, size/M, kind/documentation

#513 pipeline api: add volumClaimTemplate
  docs/content/en/references/pipeline_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/pipeline.kurator.dev_pipelines.yaml
  pkg/apis/pipeline/v1alpha1/type.go
  pkg/apis/pipeline/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/L, approved, kind/api-change, tide/merge-method-squash
