Repository kurator-dev/kurator, pull requests merged in 2023-10, with the labels that each got.

#385 Storage proposal
  docs/proposals/distributedstorage/distributedstorage.md
Labels: lgtm, size/L, approved, kind/documentation

#388 application: refactor sync resource func
  pkg/fleet-manager/application_helper.go
Labels: lgtm, size/L, approved, kind/cleanup

#390 cleanup fleet label and ownerref
  pkg/fleet-manager/controlplane.go
  pkg/fleet-manager/fleet.go
  pkg/fleet-manager/fleet_plugin.go
  pkg/fleet-manager/fleet_plugin_metric.go
  pkg/fleet-manager/util.go
Labels: lgtm, approved, size/M, kind/cleanup

#389 update golang.org/x/net
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#393 backup: update migrate api
  docs/content/en/references/backups_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/backup.kurator.dev_migrates.yaml
  pkg/apis/backups/v1alpha1/migrate_type.go
  pkg/apis/backups/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, size/M, kind/api-change

#391 doc: manage backup plugin in fleet
  docs/content/en/docs/fleet-manager/backup-plugin.md
  docs/content/en/docs/fleet-manager/image/backup-arch.svg
  docs/content/en/docs/setup/install-minio.md
Labels: lgtm, approved, size/XXL, kind/documentation

#395 Completion issues: Push fleet-manager image tagged with latest
  Makefile
Labels: lgtm, size/XS, approved

#398 cleanup: remove redundant reconciler returns when add finalizer
  pkg/cluster-operator/cluster_controller.go
  pkg/fleet-manager/application_controller.go
  pkg/fleet-manager/fleet.go
Labels: lgtm, size/XS, approved, kind/cleanup

#399 cleanup: remove unused patch option
  pkg/cluster-operator/attachedcluster_controller.go
  pkg/fleet-manager/application_controller.go
  pkg/fleet-manager/fleet.go
Labels: lgtm, size/XS, approved, kind/cleanup

#401 fix: refactor concurrent error handling with multierror group
  pkg/plugin/istio/install.go
  pkg/plugin/kubeedge/plugin.go
  pkg/plugin/pixie/vizier/plugin.go
Labels: lgtm, approved, size/M, kind/cleanup

#394 backup: init backup controller
  cmd/fleet-manager/backup/backup.go
  cmd/fleet-manager/main.go
  cmd/fleet-manager/scheme/scheme.go
  go.mod
  go.sum
  manifests/charts/fleet-manager/templates/rbac.yaml
  pkg/client/client.go
  pkg/fleet-manager/backup_controller.go
  pkg/fleet-manager/backup_restore_migrate_shared.go
Labels: lgtm, approved, kind/feature, size/XL, tide/merge-method-squash

#406 backup:add unit test for backup controller
  pkg/fleet-manager/backup-testdata/backup/include-ns.yaml
  pkg/fleet-manager/backup-testdata/backup/label-selector.yaml
  pkg/fleet-manager/backup-testdata/backup/schedule.yaml
  pkg/fleet-manager/backup_controller_test.go
  pkg/fleet-manager/backup_restore_migrate_shared_test.go
Labels: lgtm, approved, size/XL

#397 log: refactor logging to enhance clarity
  pkg/cluster-operator/attachedcluster_controller.go
  pkg/cluster-operator/cluster_controller.go
  pkg/cluster-operator/customcluster_controller.go
  pkg/cluster-operator/customcluster_scale.go
  pkg/cluster-operator/customcluster_upgrade.go
  pkg/cluster-operator/custommachine_controller.go
  pkg/fleet-manager/application_controller.go
  pkg/fleet-manager/clusters.go
  pkg/fleet-manager/fleet.go
  pkg/fleet-manager/fleet_plugin_grafana.go
  pkg/fleet-manager/fleet_plugin_metric.go
Labels: lgtm, approved, size/M, kind/cleanup

#407 backup: init restore controller
  pkg/fleet-manager/backup_restore_migrate_shared.go
  pkg/fleet-manager/backup_restore_migrate_shared_test.go
  pkg/fleet-manager/restore_controller.go
  pkg/fleet-manager/testdata/backup/include-ns.yaml
  pkg/fleet-manager/testdata/backup/label-selector.yaml
  pkg/fleet-manager/testdata/backup/schedule.yaml
  pkg/fleet-manager/testdata/restore/custom-policy.yaml
  pkg/fleet-manager/testdata/restore/minimal.yaml
Labels: lgtm, approved, kind/feature, size/XL, kind/cleanup

#408 backup: init migrate controller
  cmd/fleet-manager/backup/backup.go
  pkg/apis/backups/v1alpha1/migrate_type.go
  pkg/fleet-manager/backup_restore_migrate_shared.go
  pkg/fleet-manager/backup_restore_migrate_shared_test.go
  pkg/fleet-manager/migrate_controller.go
Labels: lgtm, size/L, approved, kind/feature, tide/merge-method-squash

#403 Unified Distributed Storage API implementation
  docs/content/en/references/fleet_v1alpha1_types.html
  docs/proposals/distributedstorage/distributedstorage.md
  go.mod
  go.sum
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleet.yaml
  pkg/apis/fleet/v1alpha1/types.go
  pkg/apis/fleet/v1alpha1/zz_generated.deepcopy.go
  pkg/client-go/generated/clientset/versioned/clientset.go
  pkg/client-go/generated/clientset/versioned/typed/apps/v1alpha1/fake/fake_application.go
  pkg/client-go/generated/clientset/versioned/typed/backups/v1alpha1/fake/fake_backup.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_attachedcluster.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_cluster.go
  pkg/client-go/generated/clientset/versioned/typed/fleet/v1alpha1/fake/fake_fleet.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/fake_customcluster.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/fake_custommachine.go
  pkg/client-go/generated/informers/externalversions/factory.go
Labels: lgtm, approved, size/XXL, tide/merge-method-squash

#405 doc:add backup dir and add backup introduce
  docs/content/en/docs/fleet-manager/backup/_index.md
  docs/content/en/docs/fleet-manager/backup/backup-plugin.md
  docs/content/en/docs/fleet-manager/backup/image/backup-arch.svg
Labels: lgtm, approved, size/M, kind/documentation, tide/merge-method-squash

#413 distributedstorage: Implementing rook installation using the fleet pl…
  pkg/fleet-manager/fleet_plugin.go
  pkg/fleet-manager/fleet_plugin_distributedstorage.go
  pkg/fleet-manager/manifests/plugins/rook-ceph.yaml
  pkg/fleet-manager/manifests/plugins/rook.yaml
  pkg/fleet-manager/plugin/plugin.go
  pkg/fleet-manager/plugin/plugin_test.go
  pkg/fleet-manager/plugin/testdata/distributedstorage/ceph-cluster-default.yaml
  pkg/fleet-manager/plugin/testdata/distributedstorage/ceph-cluster-handle.yaml
  pkg/fleet-manager/plugin/testdata/distributedstorage/default.yaml
Labels: lgtm, approved, size/XL

#415 backup: fix miss restore init controllers
  cmd/fleet-manager/backup/backup.go
Labels: lgtm, approved, size/S, kind/bug

#414 doc: how to use unified backup
  docs/content/en/docs/fleet-manager/backup/backup.md
  examples/backup/app-backup-demo.yaml
  examples/backup/backup-minimal.yaml
  examples/backup/backup-schedule.yaml
  examples/backup/backup-select-labels.yaml
  examples/backup/busybox-demo/busybox.yaml
Labels: lgtm, size/L, approved, kind/documentation

#417 doc: update doc image
  docs/content/en/docs/fleet-manager/image/fleet-application.svg
  docs/content/en/docs/fleet-manager/image/fleet-metric.png
  docs/content/en/docs/fleet-manager/image/fleet-metric.svg
  docs/content/en/docs/fleet-manager/image/fleet-policy.drawio.svg
  docs/content/en/docs/fleet-manager/image/fleet-policy.svg
  docs/content/en/docs/fleet-manager/metric-plugin.md
  docs/content/en/docs/fleet-manager/policy.md
Labels: lgtm, approved, size/XXL, kind/documentation

#418 Added a note on non-scripted creation of clusters
  docs/content/en/docs/fleet-manager/manage-attachedcluster.md
Labels: lgtm, size/XS, approved, kind/documentation

#416 Distorbutedstorage documentation
  docs/content/en/docs/fleet-manager/distributedstorage-plugin.md
  docs/content/en/docs/fleet-manager/image/distributedstorage.svg
  examples/fleet/distributedstorage/nginx-storage-demo.yaml
Labels: lgtm, approved, size/XXL

#419 add restore doc and fix restore bug
  docs/content/en/docs/fleet-manager/backup/restore.md
  examples/backup/app-backup-demo.yaml
  examples/backup/restore-minimal.yaml
  examples/backup/restore-schedule.yaml
  pkg/client-go/generated/clientset/versioned/clientset.go
  pkg/client-go/generated/clientset/versioned/typed/apps/v1alpha1/fake/fake_application.go
  pkg/client-go/generated/clientset/versioned/typed/backups/v1alpha1/fake/fake_backup.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_attachedcluster.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_cluster.go
  pkg/client-go/generated/clientset/versioned/typed/fleet/v1alpha1/fake/fake_fleet.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/fake_customcluster.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/fake_custommachine.go
  pkg/client-go/generated/informers/externalversions/factory.go
  pkg/fleet-manager/restore_controller.go
Labels: lgtm, size/L, approved, kind/bug, kind/documentation, tide/merge-method-squash

#421 add example of storage-doc
  docs/content/en/docs/fleet-manager/distributedstorage-plugin.md
  examples/fleet/distributedstorage/blockstore/block-storage-demo.yaml
  examples/fleet/distributedstorage/filesystemstore/filesystem-storage-demo.yaml
  examples/fleet/distributedstorage/objectstore/object-storage-demo.yaml
Labels: lgtm, size/L, approved, kind/documentation, cherrypick/release-0.5

#423 update kurator version
  Makefile
  docs/netlify.toml
Labels: lgtm, size/XS, approved

#425 workflows: add release image workflows
  .github/workflows/release-image.yaml
Labels: lgtm, approved, size/M, kind/feature

#427 bump version to 1.0-dev
  Makefile
  docs/netlify.toml
Labels: lgtm, size/XS, approved

#426 bugfix: make sure ns exsit when create velero secret
  pkg/fleet-manager/fleet_plugin_backup.go
Labels: lgtm, approved, size/M, kind/bug

#430 doc: update kubectl command mistake
  docs/content/en/docs/fleet-manager/backup/backup-plugin.md
  docs/content/en/docs/fleet-manager/distributedstorage-plugin.md
Labels: lgtm, size/XS, approved, kind/documentation

#433 workflows: remove 'v' prefix from tag in release image script
  .github/workflows/release-image.yaml
Labels: lgtm, approved, size/S, kind/cleanup
