Repository kurator-dev/kurator, pull requests merged in 2023-06, with the labels that each got.

#306 fleet: support plugin Kyverno
  docs/content/en/references/fleet_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleet.yaml
  pkg/apis/fleet/v1alpha1/types.go
  pkg/apis/fleet/v1alpha1/zz_generated.deepcopy.go
  pkg/fleet-manager/fleet_plugin.go
  pkg/fleet-manager/fleet_plugin_grafana.go
  pkg/fleet-manager/fleet_plugin_kyverno.go
  pkg/fleet-manager/fleet_plugin_metric.go
  pkg/fleet-manager/manifests/plugins/kyverno-policies.yaml
  pkg/fleet-manager/manifests/plugins/kyverno.yaml
  pkg/fleet-manager/plugin/plugin.go
  pkg/fleet-manager/plugin/plugin_test.go
  pkg/fleet-manager/plugin/testdata/kyverno-policies/default.yaml
  pkg/fleet-manager/plugin/testdata/kyverno/default.yaml
Labels: lgtm, approved, kind/feature, size/XL, tide/merge-method-squash

#313 chore: fix metallb not working
  hack/local-dev-setup.sh
  hack/util.sh
Labels: lgtm, size/XS, approved, kind/bug

#319 Decouple kurator fleet with karmada
  docs/content/en/references/fleet_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleet.yaml
  pkg/apis/fleet/v1alpha1/types.go
  pkg/apis/fleet/v1alpha1/zz_generated.deepcopy.go
  pkg/fleet-manager/controlplane.go
Labels: lgtm, approved, size/M, kind/api-change

#314 update fleet metric doc
  docs/content/en/docs/fleet-manager/metric-plugin.md
  examples/fleet/metric/metric-plugin.yaml
  examples/fleet/metric/monitor-demo/avalanche.yaml
Labels: lgtm, size/L, approved, kind/documentation

#311 fleet: PodSecurityPolicy support ValidationFailureAction
  docs/content/en/references/fleet_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleet.yaml
  pkg/apis/fleet/v1alpha1/types.go
  pkg/fleet-manager/plugin/plugin.go
  pkg/fleet-manager/plugin/plugin_test.go
  pkg/fleet-manager/plugin/testdata/kyverno-policies/default.yaml
Labels: lgtm, approved, size/M, kind/feature

#310 fleet: add doc for policy management
  docs/content/en/docs/fleet-manager/image/fleet-policy.drawio.svg
  docs/content/en/docs/fleet-manager/policy.md
  examples/fleet/policy/badpod-demo/badpod.yaml
  examples/fleet/policy/kyverno.yaml
Labels: lgtm, size/L, approved, kind/documentation

#320 update fleet doc after decoupling with karmada
  docs/content/en/docs/fleet-manager/create-fleet.md
  docs/content/en/docs/fleet-manager/image/fleet-manager.svg
  docs/content/en/docs/setup/install-fluxcd.md
  examples/fleet/ac1.yaml
  examples/fleet/fleet.yaml
Labels: lgtm, approved, size/XXL

#312 fleet:fix cluster copy bug
  pkg/fleet-manager/clusters.go
Labels: lgtm, size/XS, approved, kind/bug, tide/merge-method-squash

#322 Update Application API
  docs/content/en/references/apps_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/apps.kurator.dev_applications.yaml
  pkg/apis/apps/v1alpha1/types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/fleet-manager/application_controller.go
  pkg/fleet-manager/application_helper.go
Labels: lgtm, size/L, approved

#323 docs: fix branch name
  docs/content/en/docs/fleet-manager/metric-plugin.md
  docs/content/en/docs/fleet-manager/policy.md
Labels: lgtm, approved, size/S, kind/documentation

#325 fleet: update reconcileClusters to consider if controlplane specified, and update name to be consistent with current API
  docs/content/en/docs/fleet-manager/application.md
  docs/content/en/docs/fleet-manager/metric-plugin.md
  docs/content/en/docs/fleet-manager/policy.md
  examples/application/quickstart1.yaml
  examples/application/quickstart2.yaml
  pkg/fleet-manager/clusters.go
Labels: lgtm, approved, size/M

#326 fleet: kyverno policy fails if CRDs is not ready
  pkg/fleet-manager/fleet_plugin_kyverno.go
Labels: lgtm, approved, size/S, kind/bug

#328 Update kurator arch in readme
  README.md
  docs/content/en/references/cluster_v1alpha1_types.html
  docs/images/kurator-arch.svg
  docs/images/kurator.png
  manifests/charts/cluster-operator/crds/cluster.kurator.dev_clusters.yaml
  pkg/apis/cluster/v1alpha1/cluster_types.go
Labels: lgtm, approved, size/XXL

#329 update hugo version to v0.4
  docs/netlify.toml
Labels: lgtm, size/XS, approved, do-not-merge/hold

#330 docs: update homepage
  docs/assets/icons/logo.svg
  docs/assets/scss/_nav.scss
  docs/config.toml
  docs/content/en/_index.html
  docs/go.mod
  docs/go.sum
Labels: lgtm, size/L, approved, kind/documentation

#332 doc: fix metric guide
  docs/content/en/docs/fleet-manager/image/grafana-thanos.jpeg
  docs/content/en/docs/fleet-manager/image/thanos-ui.jpeg
  docs/content/en/docs/fleet-manager/metric-plugin.md
  docs/content/en/docs/fleet-manager/policy.md
  examples/fleet/metric/metric-plugin.yaml
  examples/fleet/metric/monitor-demo/avalanche.yaml
Labels: lgtm, approved, size/M, kind/documentation, tide/merge-method-squash

#335 helm: add autoGenerateCert for cluster-operator
  docs/content/en/boilerplates/install-cluster-operator.md
  docs/content/en/boilerplates/prerequisites.md
  manifests/charts/cluster-operator/templates/deployment.yaml
  manifests/charts/cluster-operator/templates/webhooks.yaml
  manifests/charts/cluster-operator/values.yaml
Labels: lgtm, approved, size/M, kind/feature, tide/merge-method-squash

#321 application: Support for more source and policy combinations
  manifests/charts/fleet-manager/templates/rbac.yaml
  pkg/fleet-manager/application_controller.go
  pkg/fleet-manager/application_helper.go
Labels: lgtm, approved, kind/feature, size/XL, tide/merge-method-squash

#340 add kubectl diplay of status on customcluster and attachedcluster
  docs/content/en/references/cluster_v1alpha1_types.html
  manifests/charts/cluster-operator/crds/cluster.kurator.dev_attachedclusters.yaml
  manifests/charts/cluster-operator/crds/infrastructure.cluster.x-k8s.io_customclusters.yaml
  pkg/apis/cluster/v1alpha1/attached_cluster_types.go
  pkg/apis/infra/v1alpha1/cluster.go
Labels: lgtm, size/L, approved, kind/api-change

#343 Revert "helm: add autoGenerateCert for cluster-operator (#335)"
  docs/content/en/boilerplates/install-cluster-operator.md
  docs/content/en/boilerplates/prerequisites.md
  manifests/charts/cluster-operator/templates/deployment.yaml
  manifests/charts/cluster-operator/templates/webhooks.yaml
  manifests/charts/cluster-operator/values.yaml
Labels: lgtm, approved, size/M

#338 customcluster: init webhook
  cmd/cluster-operator/customcluster/customcluster.go
  docs/content/en/references/infra_v1alpha1_types.html
  manifests/charts/cluster-operator/crds/infrastructure.cluster.x-k8s.io_customclusters.yaml
  manifests/charts/cluster-operator/templates/webhooks.yaml
  pkg/apis/infra/v1alpha1/cluster.go
  pkg/apis/infra/v1alpha1/zz_generated.deepcopy.go
  pkg/webhooks/customcluster_webhook.go
  pkg/webhooks/customcluster_webhook_test.go
  pkg/webhooks/testdata/customcluster/invalid-address.yaml
  pkg/webhooks/testdata/customcluster/invalid-cni-type.yaml
  pkg/webhooks/testdata/customcluster/invalid-machineref-name.yaml
  pkg/webhooks/testdata/customcluster/invalid-machineref-namespace.yaml
  pkg/webhooks/testdata/customcluster/miss-cni-type.yaml
  pkg/webhooks/testdata/customcluster/miss-machineref-all-value.yaml
  pkg/webhooks/testdata/customcluster/miss-machineref-name.yaml
  pkg/webhooks/validation_utils.go
Labels: lgtm, size/L, approved, kind/feature, kind/api-change

#334 customcluster: support kubeversion to v1.26.5
  docs/content/en/docs/cluster-operator/vms-cluster-lifecycle.md
  examples/infra/customcluster/cc-kcp.yaml
  pkg/cluster-operator/customcluster_controller.go
  pkg/cluster-operator/customcluster_helper.go
  pkg/cluster-operator/customcluster_scale.go
  pkg/cluster-operator/customcluster_upgrade.go
Labels: lgtm, approved, size/M, kind/feature, tide/merge-method-squash

#344 attachedcluster: init webhook
  cmd/cluster-operator/attachedcluster/attachedcluster.go
  manifests/charts/cluster-operator/templates/webhooks.yaml
  pkg/webhooks/attachedcluster_webhook.go
  pkg/webhooks/attachedcluster_webhook_test.go
  pkg/webhooks/testdata/attachedcluster/invalid-kubeconfig-name.yaml
  pkg/webhooks/testdata/attachedcluster/miss-kubeconfig-key.yaml
  pkg/webhooks/validation_utils.go
Labels: lgtm, size/L, approved, kind/feature

#346 update version to v0.4.0
  docs/netlify.toml
Labels: lgtm, size/XS, approved

#349 application: update doc to be consistent with code
  docs/content/en/docs/fleet-manager/application.md
Labels: lgtm, size/XS, approved, kind/documentation

#348 Add helm repo installation doc
  docs/content/en/boilerplates/build-from-source.md
  docs/content/en/boilerplates/install-cluster-operator.md
  docs/content/en/boilerplates/install-fleet-manager.md
  docs/content/en/docs/setup/insatll-kurator.md
  docs/content/en/docs/setup/install-cluster-operator.md
  docs/content/en/docs/setup/install-fleet-manager.md
  hack/release-artifacts.sh
Labels: lgtm, size/L, approved, tide/merge-method-squash

#352 doc: refactor the example of application and update doc
  docs/content/en/docs/fleet-manager/application.md
  examples/application/common/attachedcluster.yaml
  examples/application/common/fleet.yaml
  examples/application/gitrepo-helmrelease-demo.yaml
  examples/application/gitrepo-kustomization-demo.yaml
  examples/application/helmrepo-helmrelease-demo.yaml
Labels: lgtm, size/L, approved, kind/bug, kind/documentation
