Repository kurator-dev/kurator, pull requests merged in 2023-03, with the labels that each got.

#175 chore: fix chart
  manifests/charts/cluster-operator/templates/deployment.yaml
  manifests/charts/cluster-operator/templates/service.yaml
Labels: lgtm, approved, size/S, kind/bug

#176 update doc
  docs/content/en/docs/Integrations/_index.md
  docs/content/en/docs/Integrations/argocd.md
  docs/content/en/docs/Integrations/image/app-source.PNG
  docs/content/en/docs/Integrations/image/application-page.PNG
  docs/content/en/docs/Integrations/image/clusters.PNG
  docs/content/en/docs/Integrations/image/deployment-status.PNG
  docs/content/en/docs/Integrations/image/login.PNG
  docs/content/en/docs/Integrations/image/new-app.PNG
  docs/content/en/docs/Integrations/image/pixie-admin-page.png
  docs/content/en/docs/Integrations/image/pixie.png
  docs/content/en/docs/Integrations/image/sync-output.PNG
  docs/content/en/docs/Integrations/image/sync.PNG
  docs/content/en/docs/Integrations/image/thanos.png
  docs/content/en/docs/Integrations/istio.md
  docs/content/en/docs/Integrations/karmada.md
  docs/content/en/docs/Integrations/pixie-vizier.md
  docs/content/en/docs/Integrations/prerequisites-karmada.md
  docs/content/en/docs/Integrations/thanos.md
  docs/content/en/docs/cluster-operator/_index.md
  docs/content/en/docs/cluster-operator/aws-deploy.md
  docs/content/en/docs/cluster-operator/image/capa-aws.png
  docs/content/en/docs/cluster-operator/image/capa-crd.drawio
  docs/content/en/docs/cluster-operator/image/capa-crd.png
  docs/content/en/docs/cluster-operator/image/cluster-operator.drawio
  docs/content/en/docs/cluster-operator/image/cluster-operator.png
  docs/content/en/docs/cluster-operator/includes/build-from-source.tpl
  docs/content/en/docs/cluster-operator/includes/cleanup.tpl
  docs/content/en/docs/cluster-operator/includes/install-cluster-operator.tpl
  docs/content/en/docs/cluster-operator/includes/prepare-aws.tpl
  docs/content/en/docs/cluster-operator/includes/prerequisites.tpl
  docs/content/en/docs/cluster-operator/infra-api.md
  docs/content/en/docs/cluster-operator/vms-deploy.md
  docs/content/en/docs/getting-started/_index.md
  docs/content/en/docs/getting-started/quickstart.md
Labels: lgtm, approved, size/S

#181 fix webhook not working
  hack/update-crdgen.sh
  manifests/charts/cluster-operator/templates/webhooks.yaml
  manifests/config/webhooks/kustomization.yml
  pkg/apis/cluster/v1alpha1/cluster_types.go
Labels: lgtm, approved, size/S, kind/bug

#177 use exclusive CloudFormation stack
  manifests/profiles/infra/capitpls/aws.yaml.tpl
  pkg/infra/provider.go
  pkg/infra/scope/cluster.go
  pkg/infra/scope/cluster_test.go
  pkg/infra/template/aws_test.go
  pkg/infra/template/testdata/capa-quickstart.yaml
  pkg/infra/template/testdata/enable-podidentity.yaml
  pkg/infra/template/testdata/without-sshkey.yaml
Labels: lgtm, size/L, approved, kind/bug

#178 chore: remove useless params
  pkg/controllers/infra/cluster_controller.go
  pkg/infra/provider.go
Labels: lgtm, approved, size/S

#179 chore: make pollInterval configurable
  cmd/cluster-operator/infra/infra.go
  cmd/cluster-operator/main.go
  cmd/cluster-operator/options/options.go
  go.mod
  manifests/charts/cluster-operator/templates/deployment.yaml
  manifests/charts/cluster-operator/values.yaml
  pkg/controllers/infra/cluster_controller.go
  pkg/util/cmd.go
Labels: lgtm, approved, size/M

#171 Support cluster volumes
  manifests/examples/infra/quickstart.yaml
  manifests/profiles/infra/capitpls/aws.yaml.tpl
  pkg/infra/scope/cluster.go
  pkg/infra/scope/cluster_test.go
  pkg/infra/template/aws_test.go
  pkg/infra/template/testdata/with-volumes.yaml
  pkg/webhooks/cluster_webhook.go
  pkg/webhooks/cluster_webhook_test.go
  pkg/webhooks/testdata/cluster/aws-master-max-volume-exceed.yaml
  pkg/webhooks/testdata/cluster/aws-worker-max-volume-exceed.yaml
Labels: lgtm, size/L, approved, kind/bug

#183 docs: move examples under root
  docs/content/en/docs/cluster-operator/aws-deploy.md
  docs/content/en/docs/cluster-operator/includes/build-from-source.tpl
  docs/content/en/docs/cluster-operator/includes/cleanup.tpl
  docs/content/en/docs/cluster-operator/includes/install-cluster-operator.tpl
  docs/content/en/docs/cluster-operator/infra-api.md
  docs/content/en/docs/cluster-operator/vms-deploy.md
  examples/cluster/additionalresources.yaml
  examples/cluster/quickstart.yaml
  examples/infra/capi-quickstart.yaml
  examples/infra/customcluster/cc-cluster.yaml
  examples/infra/customcluster/cc-customcluster.yaml
  examples/infra/customcluster/cc-custommachine.yaml
  examples/infra/customcluster/cc-kcp.yaml
  examples/infra/multi-nodes/multi-nodes.yaml
  examples/infra/multi-tenancy/capi-multitenancy.yaml
  pkg/webhooks/cluster_webhook_test.go
Labels: lgtm, approved, size/M, kind/documentation

#174 update kubeconfig secret ref
  manifests/charts/cluster-operator/crds/cluster.kurator.dev_clusters.yaml
  manifests/charts/cluster-operator/crds/infrastructure.cluster.x-k8s.io_customclusters.yaml
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/infra/v1alpha1/cluster.go
  pkg/apis/infra/v1alpha1/zz_generated.deepcopy.go
Labels: size/M, kind/api-change

#186 rename istio cert pkg
  pkg/istiocert/cert.go
  pkg/istiocert/plugged.go
  pkg/istiocert/selfsigned.go
  pkg/plugin/istio/install.go
Labels: lgtm, approved, size/S

#187 chore: add go-import meta
  docs/layouts/_default/baseof.html
Labels: lgtm, approved, size/S

#184 doc: use boilerplates shortcode
  docs/content/en/boilerplates/build-from-source.md
  docs/content/en/boilerplates/cleanup.md
  docs/content/en/boilerplates/index.md
  docs/content/en/boilerplates/install-cluster-operator.md
  docs/content/en/boilerplates/prepare-aws.md
  docs/content/en/boilerplates/prerequisites-karmada.md
  docs/content/en/boilerplates/prerequisites.md
  docs/content/en/docs/Integrations/argocd.md
  docs/content/en/docs/Integrations/istio.md
  docs/content/en/docs/Integrations/pixie-vizier.md
  docs/content/en/docs/Integrations/thanos.md
  docs/content/en/docs/cluster-operator/aws-deploy.md
  docs/content/en/docs/cluster-operator/infra-api.md
  docs/layouts/shortcodes/boilerplate.html
Labels: lgtm, approved, size/M, kind/documentation

#185 Support Pod Identity
  docs/content/en/boilerplates/cleanup.md
  docs/content/en/docs/cluster-operator/infra-api.md
  docs/content/en/docs/cluster-operator/kurator-cluster-api.md
  examples/aws-pod-identity/pod-indentity.yaml
  examples/cluster/enable-pod-identity.yaml
  go.mod
  go.sum
  pkg/apis/cluster/v1alpha1/cluster_consts.go
  pkg/controllers/infra/cluster_controller.go
  pkg/infra/aws/aws_pod_identity.go
  pkg/infra/aws/aws_pod_identity_test.go
  pkg/infra/aws/bucket/aws_test.go
  pkg/infra/aws/bucket/s3.go
  pkg/infra/aws/bucket/s3_test.go
  pkg/infra/aws/cloudformation/template.go
  pkg/infra/aws/cloudformation/template_test.go
  pkg/infra/aws/provider.go
  pkg/infra/aws/util.go
  pkg/infra/openid/cert.go
  pkg/infra/openid/config.go
  pkg/infra/openid/discovery.json.tpl
  pkg/infra/provider/provider.go
  pkg/infra/scope/cluster.go
  pkg/infra/scope/cluster_test.go
  pkg/infra/service/pod_identity.go
  pkg/infra/template/testdata/capa-quickstart.yaml
  pkg/infra/template/testdata/enable-podidentity.yaml
  pkg/infra/template/testdata/with-volumes.yaml
  pkg/infra/template/testdata/without-sshkey.yaml
  pkg/infra/util/util.go
Labels: lgtm, approved, kind/feature, size/XXL

#188 chore: remove docs action
  .github/workflows/docs.yaml
Labels: lgtm, approved, size/M

#195 improve cluster operator doc
  Makefile
  docs/content/en/boilerplates/build-from-source.md
  docs/content/en/boilerplates/install-cluster-operator.md
  docs/content/en/docs/cluster-operator/aws-deploy.md
  docs/content/en/docs/cluster-operator/aws-irsa.md
  docs/content/en/docs/cluster-operator/kurator-cluster-api.md
  docs/content/en/docs/cluster-operator/quickstart.md
  docs/content/en/docs/cluster-operator/vms-deploy.md
  docs/layouts/shortcodes/kurator-version.html
  docs/netlify.toml
  hack/local-docsite-build.sh
  hack/local-docsite-up.sh
Labels: lgtm, size/L, approved, kind/documentation

#194 CNI render support args
  pkg/infra/plugin/plugin.go
  pkg/infra/plugin/plugin_test.go
  pkg/infra/plugin/testdata/aws-cni-custom.yaml
  pkg/infra/plugin/testdata/aws-cni-custom.yaml.tpl
  pkg/infra/plugin/testdata/cluster/cni-extra.yaml
Labels: lgtm, size/L, approved

#190 customcluster: realization of scaling of worker node
  examples/infra/customcluster/cc-customcluster.yaml
  examples/infra/customcluster/cc-custommachine.yaml
  pkg/apis/infra/v1alpha1/cluster.go
  pkg/controllers/customcluster_controller.go
  pkg/controllers/customcluster_controller_test.go
Labels: lgtm, approved, size/XL

#192 add provide precheck and fail fast
  pkg/apis/cluster/v1alpha1/cluster_consts.go
  pkg/controllers/infra/cluster_controller.go
  pkg/infra/aws/provider.go
  pkg/infra/provider/provider.go
  pkg/infra/scope/cluster.go
Labels: lgtm, size/L, approved, kind/bug

#196 bump golang 1.20
  .github/workflows/ci.yaml
  .github/workflows/release-master.yaml
  Makefile
  cmd/cluster-operator/main.go
  go.mod
  hack/golangci-lint.sh
  pkg/controllers/suite_test.go
Labels: lgtm, approved, size/S

#202 docs: remove cluster apis doc
  docs/content/en/docs/cluster-operator/aws-deploy.md
  examples/infra/capi-quickstart.yaml
  examples/infra/multi-nodes/multi-nodes.yaml
  examples/infra/multi-tenancy/capi-multitenancy.yaml
Labels: lgtm, approved, size/XL, kind/documentation

#199 update installation docs
  docs/content/en/boilerplates/build-from-source.md
  docs/content/en/boilerplates/install-cluster-operator.md
  docs/content/en/docs/cluster-operator/quickstart.md
  docs/content/en/docs/getting-started/_index.md
  docs/content/en/docs/getting-started/quickstart.md
  docs/content/en/docs/setup/_index.md
  docs/content/en/docs/setup/insatll-kurator.md
  docs/content/en/docs/setup/install-cluster-operator.md
Labels: lgtm, size/L, approved

#204 export ClusterFinalizer
  pkg/controllers/infra/cluster_controller.go
Labels: lgtm, size/XS, approved

#206 [release-0.3] export ClusterFinalizer
  pkg/controllers/infra/cluster_controller.go
Labels: lgtm, size/XS, approved

#210 rename package
  cmd/cluster-operator/infra/infra.go
  pkg/controllers/cluster_controller.go
Labels: lgtm, size/XS, approved, tide/merge-method-squash

#212 docs: fix dead link
  docs/content/en/docs/Integrations/karmada.md
Labels: lgtm, size/XS, approved, kind/documentation

#200 customcluster: add conditions
  manifests/charts/cluster-operator/crds/infrastructure.cluster.x-k8s.io_customclusters.yaml
  pkg/apis/cluster/v1alpha1/cluster_consts.go
  pkg/apis/infra/v1alpha1/cluster.go
  pkg/apis/infra/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/customcluster_controller.go
Labels: lgtm, size/L, approved

#193 doc: add customcluster scale doc
  docs/content/en/docs/cluster-operator/vms-deploy.md
Labels: lgtm, size/L, approved, kind/documentation

#207 update docs
  docs/content/en/docs/cluster-operator/_index.md
  docs/content/en/docs/cluster-operator/image/capa-aws.png
  docs/content/en/docs/cluster-operator/image/capa-crd.drawio
  docs/content/en/docs/cluster-operator/image/capa-crd.png
  docs/content/en/docs/cluster-operator/image/cluster-operator.drawio
  docs/content/en/docs/cluster-operator/image/cluster-operator.png
Labels: lgtm, size/L, approved, kind/documentation, /cherry-pick release-0.3
