Repository kurator-dev/kurator, pull requests merged in 2023-05, with the labels that each got.

#283 doc: fix fleet doc ref
  docs/content/en/docs/setup/install-cluster-operator.md
  docs/content/en/docs/setup/install-fleet-manager.md
Labels: lgtm, approved, size/S

#281 customcluster: enhance naming
  go.mod
  pkg/controllers/customcluster_controller.go
  pkg/controllers/customcluster_helper.go
  pkg/controllers/customcluster_scale.go
  pkg/controllers/customcluster_upgrade.go
Labels: lgtm, size/L, approved

#286 fleet: init monitoring api
  docs/content/en/references/fleet_v1alpha1_types.html
  hack/api-docs/config.json
  hack/api-docs/template/members.tpl
  hack/gen-api-doc.sh
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleet.yaml
  pkg/apis/fleet/v1alpha1/types.go
  pkg/apis/fleet/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, approved, size/XXL, kind/api-change

#287 attachedCluster: add controller and enable to be registered with Fleet.
  cmd/cluster-operator/attachedcluster/attachedcluster.go
  cmd/cluster-operator/main.go
  docs/content/en/references/cluster_v1alpha1_types.html
  examples/fleet/ac1.yaml
  examples/fleet/fleet.yaml
  manifests/charts/cluster-operator/crds/cluster.kurator.dev_attachedclusters.yaml
  pkg/apis/cluster/v1alpha1/attached_cluster_types.go
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/controllers/attachedcluster_controller.go
  pkg/controllers/customcluster_controller.go
  pkg/fleet-manager/clusters.go
  pkg/fleet-manager/fleet.go
Labels: lgtm, size/L, approved, kind/feature

#280 Added application sync
  cmd/fleet-manager/main.go
  docs/content/en/docs/references/app-api.md
  docs/content/en/references/apps_v1alpha1_types.html
  go.mod
  go.sum
  hack/api-docs/config.json
  hack/gen-api-doc.sh
  hack/init-codegen.sh
  hack/tool/tool.go
  hack/update-codegen.sh
  hack/update-crdgen.sh
  manifests/charts/fleet-manager/crds/apps.kurator.dev_applications.yaml
  pkg/apis/apps/v1alpha1/doc.go
  pkg/apis/apps/v1alpha1/helm_release.go
  pkg/apis/apps/v1alpha1/kustomization.go
  pkg/apis/apps/v1alpha1/types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/apps/v1alpha1/zz_generated.register.go
  pkg/client-go/generated/clientset/versioned/clientset.go
  pkg/client-go/generated/clientset/versioned/fake/clientset_generated.go
  pkg/client-go/generated/clientset/versioned/fake/register.go
  pkg/client-go/generated/clientset/versioned/scheme/register.go
  pkg/client-go/generated/clientset/versioned/typed/apps/v1alpha1/application.go
  pkg/client-go/generated/clientset/versioned/typed/apps/v1alpha1/apps_client.go
  pkg/client-go/generated/clientset/versioned/typed/apps/v1alpha1/doc.go
  pkg/client-go/generated/clientset/versioned/typed/apps/v1alpha1/fake/doc.go
  pkg/client-go/generated/clientset/versioned/typed/apps/v1alpha1/fake/fake_application.go
  pkg/client-go/generated/clientset/versioned/typed/apps/v1alpha1/fake/fake_apps_client.go
  pkg/client-go/generated/clientset/versioned/typed/apps/v1alpha1/generated_expansion.go
  pkg/client-go/generated/informers/externalversions/apps/interface.go
  pkg/client-go/generated/informers/externalversions/apps/v1alpha1/application.go
  pkg/client-go/generated/informers/externalversions/apps/v1alpha1/interface.go
  pkg/client-go/generated/informers/externalversions/factory.go
  pkg/client-go/generated/informers/externalversions/generic.go
  pkg/client-go/generated/listers/apps/v1alpha1/application.go
  pkg/client-go/generated/listers/apps/v1alpha1/expansion_generated.go
  pkg/controllers/suite_test.go
Labels: lgtm, approved, size/XXL, kind/api-change

#288 chore: update kind and metallb
  hack/kind-configs-with-worker/member1.yaml
  hack/kind-configs-with-worker/member2.yaml
  hack/kind-configs/member1.yaml
  hack/kind-configs/member2.yaml
  hack/local-dev-setup.sh
Labels: lgtm, approved, size/S

#289 doc: improve karmada integration
  docs/content/en/docs/Integrations/karmada.md
Labels: lgtm, size/XS, approved, kind/documentation

#290 chore: use seperated kubeconfig file for different cluster
  docs/content/en/docs/Integrations/karmada.md
  hack/local-dev-setup.sh
Labels: lgtm, approved, size/M

#291 chore: fix metallb not working
  hack/local-dev-setup.sh
  hack/local-setup-cluster.sh
  hack/util.sh
Labels: lgtm, size/L, approved

#292 chore: clean crd-ref-docs
  go.mod
  go.sum
  hack/tool/tool.go
Labels: lgtm, approved, size/S, kind/cleanup

#293 fleet: implement metric plugin
  cmd/fleet-manager/scheme/scheme.go
  docs/content/en/references/fleet_v1alpha1_types.html
  go.mod
  go.sum
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleet.yaml
  manifests/charts/fleet-manager/templates/rbac.yaml
  manifests/manifests.go
  manifests/profiles/fleet/plugin.tpl
  manifests/profiles/fleet/plugins/prometheus.yaml
  manifests/profiles/fleet/plugins/thanos.yaml
  pkg/apis/fleet/v1alpha1/types.go
  pkg/apis/fleet/v1alpha1/zz_generated.deepcopy.go
  pkg/fleet-manager/clusters.go
  pkg/fleet-manager/fleet.go
  pkg/fleet-manager/fleet_cluster.go
  pkg/fleet-manager/fleet_plugin.go
  pkg/fleet-manager/fleet_plugin_metric.go
  pkg/fleet-manager/plugin/plugin.go
  pkg/fleet-manager/plugin/plugin_test.go
  pkg/fleet-manager/plugin/render.go
  pkg/fleet-manager/plugin/render_test.go
  pkg/fleet-manager/plugin/testdata/prometheus/default.yaml
  pkg/fleet-manager/plugin/testdata/prometheus/with-values.yaml
  pkg/fleet-manager/plugin/testdata/thanos/custom-values.yaml
  pkg/fleet-manager/plugin/testdata/thanos/default.yaml
  pkg/fleet-manager/util.go
  pkg/infra/util/util.go
Labels: lgtm, approved, kind/feature, size/XXL

#297 Update doc
  docs/content/en/references/fleet_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleet.yaml
  pkg/apis/fleet/v1alpha1/types.go
Labels: lgtm, approved, size/S, kind/cleanup

#296 some misc fix for fleet manager
  pkg/fleet-manager/clusters.go
  pkg/fleet-manager/fleet_cluster.go
  pkg/fleet-manager/fleet_plugin.go
  pkg/fleet-manager/fleet_plugin_metric.go
Labels: lgtm, size/L, approved, kind/cleanup

#294 fleet: add metric plugin doc
  docs/content/en/docs/fleet-manager/image/fleet-metric.png
  docs/content/en/docs/fleet-manager/image/thanos-ui.jpeg
  docs/content/en/docs/fleet-manager/metric-plugin.md
  docs/content/en/docs/setup/install-fluxcd.md
  docs/content/en/docs/setup/install-minio.md
  examples/fleet/metric-plugin.yaml
  hack/local-setup-cluster.sh
Labels: lgtm, size/L, approved, kind/documentation

#300 doc: add create attachedcluster
  docs/content/en/docs/fleet-manager/manage-attachedcluster.md
Labels: lgtm, size/L, approved, kind/documentation

#302 doc: improve operator in setup kind cluster
  docs/content/en/boilerplates/build-from-source.md
  docs/content/en/boilerplates/install-fleet-manager.md
  docs/content/en/boilerplates/prerequisites.md
  docs/content/en/docs/setup/install-fleet-manager.md
  docs/content/en/docs/setup/install-minio.md
Labels: lgtm, approved, size/M, kind/documentation

#301 application: syn flux pkg with metric
  cmd/fleet-manager/scheme/flux.go
  docs/content/en/docs/setup/install-fluxcd.md
  docs/content/en/references/apps_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/apps.kurator.dev_applications.yaml
  manifests/charts/fleet-manager/templates/rbac.yaml
  pkg/apis/apps/v1alpha1/types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/fleet-manager/application_controller.go
  pkg/fleet-manager/application_helper.go
  pkg/fleet-manager/fleet_plugin.go
Labels: lgtm, size/L, approved, kind/bug, kind/api-change, kind/documentation

#303 doc: unified application distribution
  docs/content/en/docs/fleet-manager/application.md
  docs/content/en/docs/fleet-manager/image/fleet-application.svg
  examples/application/app-gitrepo.yaml
  examples/application/app-helmrepo.yaml
  examples/application/attachedcluster1.yaml
  examples/application/attachedcluster2.yaml
  examples/application/attachedcluster3.yaml
  examples/application/attachedcluster4.yaml
  examples/application/fleet-gitrepo.yaml
  examples/application/fleet-helmrepo.yaml
  examples/application/quickstart1.yaml
  examples/application/quickstart2.yaml
Labels: lgtm, approved, size/XXL, kind/documentation

#307 chore: reorg package
  cmd/cluster-operator/attachedcluster/attachedcluster.go
  cmd/cluster-operator/customcluster/customcluster.go
  cmd/cluster-operator/infra/infra.go
  pkg/cluster-operator/attachedcluster_controller.go
  pkg/cluster-operator/cluster_controller.go
  pkg/cluster-operator/customcluster_clusterconfig.template
  pkg/cluster-operator/customcluster_clusterhosts.template
  pkg/cluster-operator/customcluster_controller.go
  pkg/cluster-operator/customcluster_helper.go
  pkg/cluster-operator/customcluster_helper_test.go
  pkg/cluster-operator/customcluster_scale.go
  pkg/cluster-operator/customcluster_scale_test.go
  pkg/cluster-operator/customcluster_upgrade.go
  pkg/cluster-operator/customcluster_upgrade_test.go
  pkg/cluster-operator/custommachine_controller.go
Labels: lgtm, approved, size/M, kind/cleanup
