Repository kurator-dev/kurator, pull requests merged in 2023-11, with the labels that each got.

#437 doc: fix migrate page weight
  docs/content/en/docs/fleet-manager/backup/migrate.md
Labels: lgtm, size/XS, approved, kind/documentation

#441 Add fossa github action
  .github/workflows/fossa.yaml
Labels: lgtm, approved, size/S

#443 Update fossa.yaml
  .github/workflows/fossa.yaml
Labels: lgtm, size/XS, approved

#445 add api push key dual to github constraints
  .github/workflows/fossa.yaml
Labels: lgtm, size/XS, approved

#438 add security team
  README.md
  community/security/report-a-vulnerability.md
  community/security/security-groups.md
  community/security/vulnerability-report-template.md
Labels: lgtm, approved, size/M, kind/documentation

#447 site: add community page with existing config
  docs/content/en/community/_index.md
Labels: lgtm, size/XS, approved, kind/documentation

#449 Added provision for joining the security team
  community/security/comms-templates/join-announcement-email-list.md
  community/security/comms-templates/vulnerability-report-template.md
  community/security/private-distributors-list.md
Labels: lgtm, approved, size/M, kind/documentation

#446 site: add search function
  docs/config.toml
Labels: lgtm, size/XS, approved, kind/feature, kind/documentation, tide/merge-method-squash

#450 site: add feedback in each doc page
  docs/config.toml
Labels: lgtm, approved, size/S, kind/documentation

#453 add security readme
  community/security/README.md
Labels: lgtm, approved, size/S, kind/documentation

#455 site:fix mail naming mistake
  docs/config.toml
Labels: lgtm, size/XS, approved, kind/documentation

#454 site: add blog page
  docs/content/en/blog/0.2.0_release.md
  docs/content/en/blog/0.3.0_release.md
  docs/content/en/blog/0.4.0_release.md
  docs/content/en/blog/0.5.0_release.md
  docs/content/en/blog/_index.md
Labels: lgtm, approved, size/M, kind/documentation

#459 add security policy of Kurator
  community/security/SECURITY.md
  community/security/images/vulnerability-handling-process.PNG
Labels: lgtm, approved, size/M, kind/documentation

#466 update kubernetes version of rook
  go.mod
  go.sum
Labels: lgtm, size/L, approved, kind/bug

#464 Replaced go-scp package
  go.mod
  go.sum
  pkg/plugin/join/kubeedge/kubeedge.go
Labels: lgtm, approved, size/M, kind/bug

#462 doc: add 0.2.0 release blog to site
  docs/content/en/blog/0.2.0_release.md
  docs/content/en/blog/image/cluster-operator.png
  docs/content/en/blog/image/clusterapi-aws.png
Labels: lgtm, approved, size/M, kind/documentation

#471 doc: add 0.4 release blog to site
  docs/content/en/blog/0.4.0_release.md
Labels: lgtm, size/L, approved, kind/documentation

#472 doc: add 0.5.0 release blog to site
  docs/content/en/blog/0.5.0_release.md
Labels: lgtm, size/L, approved, kind/documentation

#470 doc: add 0.3.0 release blog to site
  docs/content/en/blog/0.3.0_release.md
  docs/content/en/blog/image/fleet-arch.png
  docs/content/en/blog/image/on-premise-vip.png
Labels: lgtm, approved, size/M, kind/documentation

#473 doc: add kurator or kubespray blog to site
  docs/content/en/blog/image/customcluster-controller.svg
  docs/content/en/blog/image/kubespray-arch.svg
  docs/content/en/blog/kurator_or_kubespray.md
Labels: lgtm, approved, size/XXL, kind/documentation

#474 doc: remove unused file in cluster operator doc
  docs/content/en/docs/cluster-operator/image/cluster-operator.drawio
  docs/content/en/docs/cluster-operator/image/cluster-operator.png
Labels: lgtm, size/L, approved, kind/documentation, kind/cleanup

#469 delete github.com/mitchellh/cli in pkg/generic
  go.mod
  go.sum
  pkg/generic/options.go
Labels: lgtm, approved, size/M, kind/bug

#480 change storage api to avoid relying on rook
  docs/content/en/references/fleet_v1alpha1_types.html
  go.mod
  go.sum
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleet.yaml
  pkg/apis/fleet/v1alpha1/types.go
  pkg/apis/fleet/v1alpha1/zz_generated.deepcopy.go
  pkg/client-go/generated/clientset/versioned/clientset.go
  pkg/client-go/generated/clientset/versioned/typed/apps/v1alpha1/fake/fake_application.go
  pkg/client-go/generated/clientset/versioned/typed/backups/v1alpha1/fake/fake_backup.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_attachedcluster.go
  pkg/client-go/generated/clientset/versioned/typed/cluster/v1alpha1/fake/fake_cluster.go
  pkg/client-go/generated/clientset/versioned/typed/fleet/v1alpha1/fake/fake_fleet.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/fake_customcluster.go
  pkg/client-go/generated/clientset/versioned/typed/infra/v1alpha1/fake/fake_custommachine.go
  pkg/client-go/generated/informers/externalversions/factory.go
  pkg/fleet-manager/plugin/plugin_test.go
  pkg/fleet-manager/plugin/testdata/distributedstorage/ceph-cluster-handle.yaml
Labels: lgtm, approved, size/XXL, kind/api-change

#485 rename fleetCluster to FleetCluster to make it public
  pkg/fleet-manager/backup_controller.go
  pkg/fleet-manager/backup_restore_migrate_shared.go
  pkg/fleet-manager/backup_restore_migrate_shared_test.go
  pkg/fleet-manager/fleet_cluster.go
  pkg/fleet-manager/fleet_plugin.go
  pkg/fleet-manager/fleet_plugin_backup.go
  pkg/fleet-manager/fleet_plugin_distributedstorage.go
  pkg/fleet-manager/fleet_plugin_grafana.go
  pkg/fleet-manager/fleet_plugin_kyverno.go
  pkg/fleet-manager/fleet_plugin_metric.go
  pkg/fleet-manager/migrate_controller.go
  pkg/fleet-manager/restore_controller.go
Labels: lgtm, approved, size/M, kind/cleanup

#488 Adding Security Policies to the Repository
  SECURITY.md
Labels: lgtm, approved, size/M, kind/documentation

#486 Bump k8s dependency to 1.27.8
  cmd/cluster-operator/attachedcluster/attachedcluster.go
  cmd/cluster-operator/aws/aws.go
  cmd/cluster-operator/capi/capi.go
  cmd/cluster-operator/customcluster/customcluster.go
  cmd/fleet-manager/application/application.go
  cmd/fleet-manager/backup/backup.go
  common/config/.golangci.yml
  go.mod
  go.sum
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleet.yaml
  pkg/cluster-operator/cluster_controller.go
  pkg/cluster-operator/customcluster_controller.go
  pkg/cluster-operator/customcluster_controller_test.go
  pkg/cluster-operator/custommachine_controller.go
  pkg/fleet-manager/application_controller.go
  pkg/fleet-manager/fleet.go
  pkg/infra/aws/provider.go
  pkg/istiocert/selfsigned.go
  pkg/plugin/istio/util.go
  pkg/plugin/prometheus/pulgin.go
  pkg/util/kube.go
  pkg/webhooks/application_webhook.go
  pkg/webhooks/attachedcluster_webhook.go
  pkg/webhooks/cluster_webhook.go
  pkg/webhooks/cluster_webhook_test.go
  pkg/webhooks/customcluster_webhook.go
  pkg/webhooks/custommachine_webhook.go
Labels: lgtm, approved, size/XXL

#483 Removed useless packages from go.mod.
  go.mod
  go.sum
Labels: lgtm, approved, size/XXL, kind/cleanup

#484 rename FleetCluster to KubeConfigSecretRef
  pkg/fleet-manager/fleet_plugin_backup.go
  pkg/fleet-manager/fleet_plugin_distributedstorage.go
  pkg/fleet-manager/fleet_plugin_kyverno.go
  pkg/fleet-manager/fleet_plugin_metric.go
  pkg/fleet-manager/plugin/plugin.go
  pkg/fleet-manager/plugin/plugin_test.go
  pkg/fleet-manager/plugin/render.go
Labels: lgtm, approved, size/M, tide/merge-method-squash, kind/cleanup
