Repository kurator-dev/kurator, pull requests merged in 2023-08, with the labels that each got.

#359 application: init webhook
  cmd/fleet-manager/application/application.go
  cmd/fleet-manager/main.go
  cmd/fleet-manager/options/options.go
  manifests/charts/cluster-operator/templates/certmanager.yaml
  manifests/charts/fleet-manager/templates/deployment.yaml
  manifests/charts/fleet-manager/templates/service.yaml
  manifests/charts/fleet-manager/templates/webhooks.yaml
  manifests/charts/fleet-manager/values.yaml
  pkg/webhooks/application_webhook.go
  pkg/webhooks/application_webhook_test.go
  pkg/webhooks/testdata/application/invalid-fleet1.yaml
  pkg/webhooks/testdata/application/invalid-fleet2.yaml
  pkg/webhooks/testdata/application/miss-default-and-policy-fleet.yaml
Labels: lgtm, size/L, approved, kind/feature, tide/merge-method-squash

#366 cluster operator: add customization for deployment
  manifests/charts/cluster-operator/templates/deployment.yaml
  manifests/charts/cluster-operator/values.yaml
Labels: lgtm, approved, size/S, kind/feature, tide/merge-method-squash

#368 Cluster controller revise
  pkg/cluster-operator/cluster_controller.go
  pkg/cluster-operator/customcluster_controller.go
Labels: lgtm, size/XS, approved

#371 doc: add output flag for curl release package
  docs/content/en/docs/setup/insatll-kurator.md
  docs/content/en/docs/setup/install-cluster-operator.md
  docs/content/en/docs/setup/install-fleet-manager.md
Labels: lgtm, size/XS, approved, kind/documentation

#372 doc: add proposal template
  docs/proposals/proposal-template/proposal-template.md
Labels: lgtm, size/L, approved, kind/documentation

#373 Unit test for CustomClusterController
  go.mod
  go.sum
  pkg/cluster-operator/customcluster_controller_test.go
Labels: lgtm, approved, size/XL, tide/merge-method-squash

#376 API: update kubectl display printcolumn
  docs/content/en/references/apps_v1alpha1_types.html
  docs/content/en/references/infra_v1alpha1_types.html
  manifests/charts/cluster-operator/crds/cluster.kurator.dev_attachedclusters.yaml
  manifests/charts/cluster-operator/crds/infrastructure.cluster.x-k8s.io_customclusters.yaml
  manifests/charts/cluster-operator/crds/infrastructure.cluster.x-k8s.io_custommachines.yaml
  pkg/apis/apps/v1alpha1/types.go
  pkg/apis/cluster/v1alpha1/attached_cluster_types.go
  pkg/apis/infra/v1alpha1/cluster.go
  pkg/apis/infra/v1alpha1/machine.go
Labels: lgtm, approved, size/M, kind/api-change, kind/documentation
