Repository kurator-dev/kurator, pull requests merged in 2024-01, with the labels that each got.

#533 pipeline: update pipeline proposal cli design
  docs/proposals/pipeline/pipeline.md
Labels: lgtm, approved, size/M, kind/feature, kind/documentation, kind/design

#534 pipeline: complete pipeline list cli
  cmd/kurator/app/app.go
  cmd/kurator/app/pipeline/execution/execution.go
  cmd/kurator/app/pipeline/execution/list/list.go
  cmd/kurator/app/pipeline/pipeline.go
  pkg/pipeline/execution/list/list.go
  pkg/pipeline/execution/list/list_test.go
Labels: lgtm, size/L, approved, kind/feature

#537 pipeline: complete pipeline logs cli
  cmd/kurator/app/pipeline/execution/execution.go
  cmd/kurator/app/pipeline/execution/logs/logs.go
  pkg/pipeline/execution/logs/logs.go
Labels: lgtm, size/L, approved, kind/feature, tide/merge-method-squash

#541 pipeline: add render custom task func
  pkg/fleet-manager/pipeline/render/customTask.go
  pkg/fleet-manager/pipeline/render/customTask_test.go
  pkg/fleet-manager/pipeline/render/testdata/custom-task/cat-readme.yaml
  pkg/fleet-manager/pipeline/render/testdata/custom-task/cmd-args-task.yaml
  pkg/fleet-manager/pipeline/render/testdata/custom-task/complete-task.yaml
  pkg/fleet-manager/pipeline/render/testdata/custom-task/env-task.yaml
  pkg/fleet-manager/pipeline/render/testdata/custom-task/minimal-task.yaml
  pkg/fleet-manager/pipeline/render/testdata/custom-task/resource-task.yaml
  pkg/fleet-manager/pipeline/render/util.go
Labels: lgtm, size/L, approved, kind/feature

#551 change the RolloutTimeoutSeconds to be of type *int32
  docs/content/en/references/apps_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/apps.kurator.dev_applications.yaml
  pkg/apis/apps/v1alpha1/types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
Labels: lgtm, size/XS, approved, kind/api-change

#529 complete rollout policy controller render
  manifests/charts/fleet-manager/templates/rbac.yaml
  pkg/fleet-manager/application/helper.go
  pkg/fleet-manager/application/manifests/rollout_testloader.go
  pkg/fleet-manager/application/manifests/rollout_testloader_test.go
  pkg/fleet-manager/application/manifests/testdata/testloader-deploy.yaml
  pkg/fleet-manager/application/manifests/testdata/testloader-svc.yaml
  pkg/fleet-manager/application/rollout_helper.go
  pkg/fleet-manager/application/rollout_helper_test.go
Labels: lgtm, approved, kind/feature, size/XXL

#547 pipeline: add render trigger func
  pkg/fleet-manager/pipeline/render/testdata/trigger/default.yaml
  pkg/fleet-manager/pipeline/render/testdata/trigger/with-volume-claim.yaml
  pkg/fleet-manager/pipeline/render/trigger.go
  pkg/fleet-manager/pipeline/render/trigger_test.go
Labels: lgtm, size/L, approved, kind/feature

#545 pipeline: add render predefined task func
  pkg/fleet-manager/pipeline/render/predefined_task.go
  pkg/fleet-manager/pipeline/render/predefined_task_content.go
  pkg/fleet-manager/pipeline/render/predefined_task_test.go
  pkg/fleet-manager/pipeline/render/testdata/predefined-task/build-and-push-image-custom.yaml
  pkg/fleet-manager/pipeline/render/testdata/predefined-task/build-and-push-image-default.yaml
  pkg/fleet-manager/pipeline/render/testdata/predefined-task/git-clone.yaml
  pkg/fleet-manager/pipeline/render/testdata/predefined-task/go-lint-advanced-config.yaml
  pkg/fleet-manager/pipeline/render/testdata/predefined-task/go-lint-custom-value.yaml
  pkg/fleet-manager/pipeline/render/testdata/predefined-task/go-test-custom-value.yaml
  pkg/fleet-manager/pipeline/render/testdata/predefined-task/go-test-default.yaml
Labels: lgtm, approved, kind/feature, size/XXL, tide/merge-method-squash

#552 pipeline: update the api field json
  docs/content/en/references/pipeline_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/pipeline.kurator.dev_pipelines.yaml
  pkg/apis/pipeline/v1alpha1/type.go
Labels: lgtm, size/L, approved, kind/bug, kind/api-change

#548 pipeline: add render pipeline func
  pkg/fleet-manager/pipeline/render/pipeline.go
  pkg/fleet-manager/pipeline/render/pipeline_test.go
  pkg/fleet-manager/pipeline/render/testdata/pipeline/comprehensive.yaml
  pkg/fleet-manager/pipeline/render/testdata/pipeline/readme-test.yaml
Labels: lgtm, size/L, approved, kind/feature, tide/merge-method-squash

#555 fix bug where function `installPrivateTestloader()` only install in the control plant
  pkg/fleet-manager/application/rollout_helper.go
Labels: lgtm, approved, size/M, kind/bug

#554 doc: add practical operation guild for pipeline
  docs/content/en/docs/pipeline/image/webhook.png
  docs/content/en/docs/pipeline/operation.md
Labels: lgtm, size/L, approved, kind/documentation

#497 add a distributors application issue template
  .github/ISSUE_TEMPLATE/distributors-application.md
Labels: lgtm, approved, size/S, kind/documentation

#540 doc: add pipeline api reference
  docs/content/en/docs/references/app-api.md
  docs/content/en/docs/references/backup-api.md
  docs/content/en/docs/references/cluster-api.md
  docs/content/en/docs/references/fleet-api.md
  docs/content/en/docs/references/infra-api.md
  docs/content/en/docs/references/pipeline-api.md
Labels: lgtm, approved, size/S, kind/documentation

#550 doc: add doc of setting up your pipeline
  docs/content/en/docs/pipeline/setting.md
Labels: lgtm, size/L, approved, kind/documentation, tide/merge-method-squash

#553 pipeline: fix render rbac for chain secret
  pkg/fleet-manager/pipeline/render/rbac.go
  pkg/fleet-manager/pipeline/render/rbac_test.go
  pkg/fleet-manager/pipeline/render/testdata/rbac/default-example.yaml
Labels: lgtm, approved, size/S, kind/bug

#556 add handling for getting rollout status
  pkg/fleet-manager/application/controller.go
  pkg/fleet-manager/application/rollout_helper.go
  pkg/fleet-manager/application/rollout_helper_test.go
Labels: lgtm, size/L, approved, kind/feature

#543 doc: add pipeline overview
  docs/content/en/docs/pipeline/_index.md
  docs/content/en/docs/pipeline/image/pipeline-arch.svg
  docs/content/en/docs/pipeline/image/use-pipeline.svg
Labels: lgtm, approved, size/XXL, kind/documentation, tide/merge-method-squash

#557 adds the ability to delete resources created by a Rollout.
  pkg/fleet-manager/application/controller.go
  pkg/fleet-manager/application/rollout_helper.go
Labels: lgtm, approved, size/M, kind/feature

#558 doc: add cleanup part in pipeline operation
  docs/content/en/docs/pipeline/operation.md
Labels: lgtm, approved, size/S, kind/documentation

#562 fix incorrect expression of rolloutStatus
  docs/content/en/references/apps_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/apps.kurator.dev_applications.yaml
  pkg/apis/apps/v1alpha1/types.go
Labels: lgtm, approved, size/S, kind/api-change

#549 Rollout plugin doc
  docs/content/en/docs/fleet-manager/rollout/image/rollout.svg
  docs/content/en/docs/fleet-manager/rollout/rollout-plugin.md
Labels: lgtm, size/L, approved, kind/documentation

#563 doc: fix pipeline doc mistake
  docs/content/en/docs/pipeline/operation.md
  docs/content/en/docs/pipeline/setting.md
Labels: lgtm, approved, size/S, kind/bug, kind/documentation

#560 add canary deployment doc
  docs/content/en/docs/fleet-manager/rollout/canary.md
  docs/content/en/docs/fleet-manager/rollout/image/canary.svg
  examples/rollout/canary.yaml
Labels: lgtm, size/L, approved, kind/documentation

#566 doc: fix pipeline operation cli mistake
  docs/content/en/docs/pipeline/operation.md
Labels: lgtm, size/XS, approved, kind/documentation

#564 add A/B Testing doc
  docs/content/en/docs/fleet-manager/rollout/abtest.md
  docs/content/en/docs/fleet-manager/rollout/image/abtesting.svg
  examples/rollout/ab-testing.yaml
Labels: lgtm, size/L, approved, kind/documentation

#559 pipeline: init pipeline controller
  cmd/fleet-manager/main.go
  cmd/fleet-manager/pipeline/pipeline.go
  cmd/fleet-manager/scheme/scheme.go
  pkg/fleet-manager/pipeline/controller.go
Labels: lgtm, size/L, approved, kind/feature, kind/design

#571 fix pipeline doc
  docs/content/en/docs/pipeline/operation.md
  docs/content/en/docs/pipeline/setting.md
Labels: lgtm, size/XS, approved, kind/documentation

#570 doc: add pipeline guild for supply chain security
  docs/content/en/docs/pipeline/chain-security.md
  docs/content/en/docs/pipeline/image/chain-security.png
  docs/content/en/docs/pipeline/setting.md
Labels: lgtm, size/L, approved, kind/documentation

#572 fix remove ‘v' in image version error
  .github/workflows/release-image.yaml
Labels: lgtm, approved, size/S, cherrypick/release-0.6

#568 add Licences restrictions in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: lgtm, approved, size/M, kind/documentation

#575 add remove application finalizer
  pkg/fleet-manager/application/controller.go
Labels: lgtm, size/XS, approved

#577 update doc version to 0.6.0
  docs/netlify.toml
Labels: lgtm, size/XS, approved, cherrypick/release-0.6

#580 delete functionally similar yaml packages
  go.mod
  pkg/fleet-manager/application/rollout_helper.go
  pkg/plugin/prometheus/testdata/prometheus-additional.yaml
  pkg/plugin/prometheus/util.go
  pkg/util/policy_test.go
Labels: lgtm, approved, size/M, kind/cleanup

#579 Fixed the script name of licenses-check in the makefile.
  Makefile
  hack/licenses-check.sh
Labels: lgtm, size/XS, approved

#581 Fixed CI licenses lint passing when encountering unrecognised licenses
  .github/workflows/ci.yaml
Labels: lgtm, size/XS, approved

#585 add List of licences now used by kurator
  community/open-source-security/allowed-licenses-list.md
Labels: lgtm, approved, size/M, kind/documentation

#584 add notice about kurator
  NOTICE
Labels: lgtm, approved, size/S, kind/documentation

#583 add a doc about dependence-compliance of kurator
  community/compliance/dep-approvers.md
  community/compliance/dependence-compliance.md
Labels: lgtm, size/L, approved, kind/documentation

#586 Automate --kubeconfig in kurator CLI to default to kurator-host.config
  pkg/generic/options.go
Labels: lgtm, size/XS, approved

#591 introduce github actions prow
  .github/workflows/prow.yaml
Labels: size/S

#593 Revert "introduce github actions prow"
  .github/workflows/prow.yaml
Labels: size/S

#588 sign kurator images
  .github/workflows/release-image.yaml
  Makefile
  hack/image-sign.sh
Labels: lgtm, approved, size/M, tide/merge-method-squash

#589 change allow-licenses-list dir and add clarification about dependence in CONTRIBUTING.md
  CONTRIBUTING.md
  community/compliance/allowed-licenses-list.md
  community/compliance/dependence-compliance.md
Labels: lgtm, approved, size/S
