Repository kurator-dev/kurator, pull requests merged in 2024-06, with the labels that each got.

#644 fix unified distributed storage doc title
  docs/content/en/docs/fleet-manager/distributedstorage-plugin.md
Labels: lgtm, size/XS, approved

#646 add kurator playgroud link in docs
  docs/content/en/docs/fleet-manager/application.md
  docs/content/en/docs/setup/insatll-kurator.md
Labels: lgtm, size/XS, approved, kind/documentation

#639 Fix: typo of file and func name
  pkg/fleet-manager/fleet_plugin_flagger.go
  pkg/fleet-manager/plugin/plugin.go
  pkg/fleet-manager/plugin/plugin_test.go
  pkg/plugin/prometheus/plugin.go
Labels: lgtm, approved, size/S, kind/bug
