Repository kurator-dev/kurator, pull requests merged in 2024-08, with the labels that each got.

#659 doc: fs.inotify hint for karmada deploy
  docs/content/en/docs/Integrations/karmada.md
  docs/content/en/docs/fleet-manager/manage-attachedcluster.md
Labels: lgtm, size/XS, approved

#662 Fix: Update Makefile for Unlink error
  Makefile
Labels: lgtm, size/XS, approved, kind/bug

#658 proposal: submariner as fleet plugin
  docs/proposals/submariner/submariner_as_fleet_plugin.md
Labels: lgtm, approved, size/M, kind/feature

#680 Fix: sleep a while after deleting cluster when setting up
  hack/util.sh
Labels: lgtm, size/L, approved, kind/bug

#675 fix: Wrong return value
  pkg/fleet-manager/fleet_plugin_metric.go
  pkg/plugin/istio/install.go
  pkg/plugin/prometheus/plugin.go
Labels: lgtm, size/XS, approved, kind/bug

#654 proposal:Single cluster deployment application
  docs/proposals/application/single_cluster_deployment_application.md
Labels: lgtm, approved, size/M, kind/feature, kind/api-change

#672 update doc
  docs/content/en/docs/fleet-manager/rollout/abtest.md
  docs/content/en/docs/fleet-manager/rollout/blue-green.md
  docs/content/en/docs/fleet-manager/rollout/canary.md
Labels: lgtm, approved, size/S, kind/documentation

#674 Fix: Remove redundant APIs and change incorrect comments
  docs/content/en/references/backups_v1alpha1_types.html
  docs/content/en/references/fleet_v1alpha1_types.html
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleets.yaml
  pkg/apis/backups/v1alpha1/common_type.go
  pkg/apis/backups/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/fleet/v1alpha1/types.go
  pkg/fleet-manager/application/controller.go
Labels: lgtm, approved, size/M, kind/cleanup

#671 Update stale Helm install flag
  cmd/cluster-operator/README.md
  docs/content/en/boilerplates/prerequisites.md
  hack/e2e-test/install-kurator.sh
Labels: lgtm, size/XS, approved, kind/cleanup

#679 Feat: Add Codespell Check CI
  .codespellrc
  .github/workflows/code-spell.yml
  CODE_OF_CONDUCT.md
  cmd/kurator/app/pipeline/execution/logs/logs.go
  docs/README.md
  docs/content/en/docs/Integrations/istio.md
  docs/content/en/docs/Integrations/pixie-vizier.md
  docs/content/en/docs/fleet-manager/_index.md
  docs/content/en/docs/fleet-manager/application.md
  docs/content/en/docs/fleet-manager/distributedstorage-plugin.md
  docs/content/en/docs/fleet-manager/manage-attachedcluster.md
  docs/content/en/docs/fleet-manager/rollout/abtest.md
  docs/content/en/docs/fleet-manager/rollout/blue-green.md
  docs/content/en/docs/fleet-manager/rollout/canary.md
  docs/content/en/docs/pipeline/setting.md
  docs/content/en/references/apps_v1alpha1_types.html
  docs/content/en/references/fleet_v1alpha1_types.html
  docs/proposals/rollout/rollout.md
  hack/util.sh
  manifests/charts/fleet-manager/crds/apps.kurator.dev_applications.yaml
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleets.yaml
  manifests/profiles/infra/plugins/aws-cni-calico.yaml
  pkg/apis/apps/v1alpha1/types.go
  pkg/apis/cluster/v1alpha1/cluster_consts.go
  pkg/apis/fleet/v1alpha1/types.go
  pkg/client/client.go
  pkg/fleet-manager/application/rollout_helper.go
  pkg/fleet-manager/controlplane.go
  pkg/infra/aws/aws_pod_identity.go
  pkg/infra/plugin/testdata/aws-cni-calico.yaml
  pkg/plugin/istio/install.go
  pkg/plugin/prometheus/plugin.go
  pkg/plugin/volcano/plugin.go
Labels: lgtm, size/L, approved, kind/feature

#667 Feat: Single cluster deployment application
  docs/content/en/references/apps_v1alpha1_types.html
  examples/application/gitrepo-kustomization-demo-without-fleet.yaml
  manifests/charts/fleet-manager/crds/apps.kurator.dev_applications.yaml
  pkg/apis/apps/v1alpha1/types.go
  pkg/fleet-manager/application/controller.go
  pkg/fleet-manager/application/helper.go
  pkg/fleet-manager/application/rollout_helper.go
  pkg/fleet-manager/fleet_cluster.go
  pkg/webhooks/application_webhook.go
  pkg/webhooks/application_webhook_test.go
Labels: lgtm, size/L, approved, kind/feature

#660 Feat: Install submariner as fleet plugin
  docs/content/en/references/fleet_v1alpha1_types.html
  examples/fleet/network/submariner-plugin.yaml
  manifests/charts/fleet-manager/crds/fleet.kurator.dev_fleets.yaml
  pkg/apis/fleet/v1alpha1/types.go
  pkg/apis/fleet/v1alpha1/zz_generated.deepcopy.go
  pkg/fleet-manager/fleet_plugin.go
  pkg/fleet-manager/fleet_plugin_submariner.go
  pkg/fleet-manager/manifests/plugins/sm-broker.yaml
  pkg/fleet-manager/manifests/plugins/sm-operator.yaml
  pkg/fleet-manager/plugin/plugin.go
  pkg/fleet-manager/plugin/plugin_test.go
  pkg/fleet-manager/plugin/testdata/sm-broker/default.yaml
  pkg/fleet-manager/plugin/testdata/sm-operator/default.yaml
Labels: lgtm, approved, kind/feature, size/XL, kind/api-change

#683 Feat: Add customizable Metrics Analysis to the rollout API
  docs/content/en/references/apps_v1alpha1_types.html
  examples/rollout/canaryWithCustomMetric.yaml
  manifests/charts/fleet-manager/crds/apps.kurator.dev_applications.yaml
  pkg/apis/apps/v1alpha1/types.go
  pkg/apis/apps/v1alpha1/zz_generated.deepcopy.go
  pkg/fleet-manager/application/rollout_helper.go
  pkg/fleet-manager/application/rollout_helper_test.go
Labels: lgtm, size/L, approved, kind/feature, kind/api-change

#684 Doc:Single cluster deployment application
  docs/content/en/docs/fleet-manager/application.md
  examples/application/gitrepo-kustomization-demo-without-fleet.yaml
Labels: lgtm, approved, size/M, kind/documentation

#668 Doc: Add Fleet submariner plugin doc
  docs/content/en/docs/fleet-manager/submariner-plugin.md
Labels: lgtm, size/L, approved, kind/documentation
