Repository kurator-dev/kurator, pull requests merged in 2024-04, with the labels that each got.

#616 add LiZhenCheng9527 to reviewer
  OWNERS
Labels: lgtm, size/XS, approved

#617 Automatically create the directory if it does not exist
  cmd/crd-gen-tool/main.go
Labels: lgtm, size/XS, approved, kind/bug

#618 Fix shell script incompatibility on mac system
  hack/e2e-test/build-clusters.sh
  hack/gen-chart.sh
  hack/local-dev-setup.sh
  hack/sync-crds.sh
  hack/util.sh
Labels: lgtm, approved, size/M, kind/bug
